### ISSUE TITLE
IndexHierarchy display to show underlying Index types

### ISSUE THREAD

**Issue by flexatone** [InvestmentSystems/static-frame#102]
Add another row to header display of IndexHierarchy to show the Index type per depth composed in the IH. Similarly, NP type should be drawn form composed index, not aggregated IH values.

**Comment by chaburkland** [comment]
@flexatone I think this issue has been addressed:
```python
ih = sf.IndexHierarchy.from_product(('I', 'II'), ('B', 'A'), (True, False))

print(ih)
<IndexHierarchy>
I                B     True
I                B     False
I                A     True
I                A     False
II               B     True
II               B     False
II               A     True
II               A     False
<<U2>            <<U1> <bool>
```

**Comment by flexatone** [comment]
Thanks for looking at this. This was in regard to not the dtype, but the Index subclass, if used, for each depth of the IndexHierarchy. Now that 0.9 will force a one-to-one relationship between `datetime64` unit and Index subclass, this feature is probably no longer needed, unless we find other types Index subclasses. I will close this ticket for now.
