### ISSUE TITLE
Support pathlib

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#107]
`pathlib.Path`s are a convenient, cross platform way to work with paths. It would be nice if static frame's io methods supported them.

Adding support *could* be as easy as calling `str` on `Path` objects to get regular string paths, but it could also make use of higher level interfaces like `Path.write_text` (which handles opening and closing files for you) or at least `Path.open`.

**Comment by flexatone** [comment]
Agreed! Thanks for pointing this out. We will review all file path interfaces and add Pathlib support.

**Comment by flexatone** [comment]
This has been completed for all input/output methods take a file path, including CSV, TSV, XLSX, SQLite, and HDF5, and will be available in the 0.5.0 release.
