### ISSUE TITLE
How about to make sort_*() keyword only?

### ISSUE THREAD

**Issue by nekobon** [InvestmentSystems/static-frame#115]
I was trying to sort a frame by values in a column, and I was mistakenly using `Frame.sort_columns(my_col_name)`. The method ran by using `my_col_name` as a bool (i.e.`ascending=True`). This time the column names were already in sorted order, so it was difficult to realize that I called a wrong method.

How about to make sort*() methods keyword only? Or at least make `ascending` a keyword instead of positional argument?

**Comment by flexatone** [comment]
This is an excellent observation and suggestion. I have made changes to the following functions to make all arguments, except the `key` argument of `Frame.sort_values`, keyword only:

`Frame.sort_index`
`Frame.sort_columns`
`Frame.sort_values`
`Series.sort_index`
`Series.sort_values`
