### ISSUE TITLE
Frame.from_tsv replaces spaces with underscores in column names. 

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#121]
Another 'maybe fixed in 0.5' issue:

```python
fp = '/tmp/tmp.tsv'
f = sf.Frame([1, 2, 3], columns=['with space'])
<Frame>
<Index> with space <<U10>
<Index>
0       1
1       2
2       3
<int64> <int64>

f.to_tsv(fp)
f2 = sf.Frame.from_tsv(fp)
f2
<Frame>
<Index> index   with_space <<U10>
<Index>
0       0       1
1       1       2
2       2       3
<int64> <int64> <int64>
```

Note that the column `with space` was replaced with `with_space`. This happens on load, as the underlying tsv still has the space.

**Comment by flexatone** [comment]
Thank you for posting this issue.

This is an artifact of using `np.genfromtxt` to parse the column names and return them as dtype labels in a  structured array. As I already treated `column_depth > 1` as a special case of column processing, I have been able to fix this issue by always processing column labels independently of structured array formation.

So in 0.5 this will work as expected:
```python
>>> import static_frame as sf
>>> f1 = sf.Frame([1, 2, 3], columns=['with space'])
>>> f1
<Frame>
<Index> with space <<U10>
<Index>
0       1
1       2
2       3
<int64> <int64>
>>> f1.to_tsv('/tmp/tmp.txt')

>>> sf.Frame.from_tsv('/tmp/tmp.txt', index_depth=1)
<Frame>
<Index> with space <<U10>
<Index>
0       1
1       2
2       3
<int64> <int64>
```
