### ISSUE TITLE
Frame.to_pandas coerces float to object

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#123]
Similar to #122, a column of floats in a `Frame` becomes a column of `object` when converted to pandas. The `object` in this case is a python `float`. 

```python
f = sf.FrameGO(['a' for x in range(5)], columns=['a'])
f['b'] = [1.0 for i in range(5)]
f.dtypes
<Series>
<Index>
a        <U1
b        float64
<<U1>    <object>

p = f.to_pandas()
p.dtypes
a    object
b    object
dtype: object
```

**Comment by flexatone** [comment]
Thank you for posting this issue!

The first implementation of this had created the Pandas DF from the `.values` representation of the underlying data. This forces coercion to a single NumPy type, and is clearly undesirable. I have reimplemented this functionality to load one column at a time into the DF, preserving the underlying types. This will be part of the 0.5 release.

```python
>>> import static_frame as sf
>>> f = sf.FrameGO(['a' for x in range(5)], columns=['a'])
>>> f['b'] = [1.0 for i in range(5)]
>>> f
<FrameGO>
<IndexGO> a     b         <<U1>
<Index>
0         a     1.0
1         a     1.0
2         a     1.0
3         a     1.0
4         a     1.0
<int64>   <<U1> <float64>
>>> f.to_pandas().dtypes
a     object
b    float64
dtype: object
```
