### ISSUE TITLE
Frame.iter_tuple with axis 0 fails when index contains things that aren't valid identifiers

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#127]
I found this by accident when I couldn't remember which axis to use to iterate over rows (axis 0 iterates over columns).

```python
list(sf.Frame(range(5)).iter_tuple(axis=0))
builtins.ValueError: Type names and field names must be valid identifiers: '0'
```

The issue is that we can't create `namedtuple`s with numeric field names. If we want to support column-wise tuple iteration (and do we? The use case seems limited), namedtuple may not be the best choice. 

Options I can think of are:

1. Use namedtuple's `rename` argument
2. Fail over to regular tuples, like pandas does
3. Add a prefix to indexes before making fields out of them, e.g., `Tuple = namedtuple('Axis', (f'index_{x}' for x in self._index.values))`

**Comment by flexatone** [comment]
Thanks for isolating this issue.

Note that all `Frame` iterators such as these (`iter_tuple`, `iter_array`, `iter_series`) all take an axis argument, so the common interface is desirable. And while `iter_series_items(axis=0)` is identical to `Frame.items()`, it is practical to iterate column values as tuples (as they are potentially hashable, where NP arrays are not) or arrays, depending on the needs of the calling code (or the function application available with the `.apply_*` methods.

That said, I had left undecided how to handle invalid identifiers as field labels in NamedTuples. My preference at this time is do (2), fall back on regular tuples. I think this is far less surprising than generating new labels, either manually or with `rename=True`. Any concerns with that approach?

**Comment by flexatone** [comment]
This fix is implemented and will be release as part of 0.5.1.

```python
In [1]: import static_frame as sf                                                                                                                                                                                       

In [2]: tuple(sf.Frame(range(5)).iter_tuple(axis=0))                                                                                                                                                                    
Out[2]: ((0, 1, 2, 3, 4),)```

**Comment by ForeverWintr** [comment]
You're fast! I was still mulling your question. I think that approach is fine... Dynamically changing types seems a little distasteful, but perhaps this is a case of practicality beating purity.

**Comment by flexatone** [comment]
I agree that dynamically changing types is undesirable. In this case, I think that it less awkward since NamedTuple is a subclass of tuple.
