### ISSUE TITLE
Series/Frame.from_concat() raises on empty iterable

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/static-frame#135]
`Frame.from_concat()` and `Series.from_concat()` both raise `StopIteration` exceptions when passed an empty iterable. One of two things should happen instead of this:

1) Return an empty Series/Frame when `from_concat()` is called with an empty iterable.
2) Raise a different exception (or even an assert failure), as `StopIteration` is not clear.

My recommendation is 1), as that feels the most intuitive. If my argument contains no values, I expect to receive a Series/Frame that also contains no values.

**Comment by brandtbucher** [comment]
I'd even go so far as to say that (1) is the *expected* behavior, and this is a bug.

**Comment by brandtbucher** [comment]
This also affects `Frame.from_concat_items` / `Series.from_concat_items`. Fixing it should be as simple as wrapping the call to `next` in a `try`/`except` block...

**Comment by flexatone** [comment]
Thanks to @chaburkland for the fix!
