### ISSUE TITLE
Frame.assign not optimally handling dtypes on __getitem__ assignments

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/static-frame#136]
When calling `__getitem__` on `Frame.assign`'s interface, it is making incorrect dtype assignments.

See this example:
```
>>> f1 = sf.Frame(False, index=range(2), columns=tuple('ab'))
>>> f1
<Frame>
<Index> a      b      <<U1>
<Index>
0       False  False
1       False  False
<int64> <bool> <bool>

>>> f2 = f1.assign['a']([1,2])
>>> f2
<Frame>
<Index> a        b        <<U1>
<Index>
0       1        False
1       2        False
<int64> <object> <object>

>>> f1._blocks._blocks
[array([[False, False],
        [False, False]])]

>>> f2._blocks._blocks
[array([[1, False],
        [2, False]], dtype=object)]
```
It appears that the underlying block structure is not being split into columns, and thus the 2D array has to be downcast to `object` since that is the closest parent type to `bool` and `int64`.

**Comment by flexatone** [comment]
Many thanks of isolating this issue.

Correcting this issue, I have reimplemented `Frame` assignment (via `TypeBlocks`) to maximally preserve column types in assignment, either when assigning whole columns (where the type will be the type of the assigned values) or values within a column (where the type will be a compatible type between the former and assigned value type). In all cases, only columns affected  by assignment will have their types changed. This new implementation is also more efficient, in that it requires less copying of underlying data and more reuse of immutable arrays.

This has been fixed and will be part of the 0.5.10 release.

```python
>>> f1 = sf.Frame(False, index=range(2), columns=tuple('ab'))
>>> f1
<Frame>
<Index> a      b      <<U1>
<Index>
0       False  False
1       False  False
<int64> <bool> <bool>

>>> f1.assign['a']([1,2])
<Frame>
<Index> a       b      <<U1>
<Index>
0       1       False
1       2       False
<int64> <int64> <bool>

>>> f1.assign.loc[1, 'b']('x')
<Frame>
<Index> a      b        <<U1>
<Index>
0       False  False
1       False  x
<int64> <bool> <object>
```
