### ISSUE TITLE
Frame.to_xlsx drops column name when include_index is False

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#138]
```python
a = sf.Frame(range(3, 6), columns=['column_a'])
a.to_xlsx('/tmp/tmp.xlsx', include_index=False)
```

Results in the following sheet, with no column label:
![image](https://user-images.githubusercontent.com/3046190/70181336-8e81d400-1696-11ea-90de-f7d0100d227a.png)

**Comment by flexatone** [comment]
Thanks for isolating this issue! This is also now fixed as part of the changes for the related issue.

See this and the following tests for examples:
https://github.com/InvestmentSystems/static-frame/blob/be4056d8d1e0a290c537cd562af24738e389e3a6/static_frame/test/unit/test_store_xlsx.py#L98
