### ISSUE TITLE
Index name isn't preserved when selecting with loc.

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#142]
```python
a = sf.Frame(range(3), index=sf.Index(tuple('abc'), name='INDEX'))
a.loc['b':].index.name # None
```

I think it makes sense to preserve index name in this case, because we are effectively selecting a subset of the original index.

**Comment by flexatone** [comment]
Thanks for isolating this issue. I have expanded the propagation of `name` attributes for `Index` and `IndexHierarchy`. This will be part of the 0.5.8 release.

```python
>>> a = sf.Frame(range(3), index=sf.Index(tuple('abc'), name='INDEX'))
>>> a.loc['b':].index.name
'INDEX'
```
