### ISSUE TITLE
FrameGO.from_xlsx returns a Frame

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#154]
```python
sf.Frame(range(3, 6), columns=['a']).to_xlsx('/tmp/tmp.xlsx')
type(sf.FrameGO.from_xlsx('/tmp/tmp.xlsx'))
# <class 'static_frame.core.frame.Frame'>
```

It looks like `StoreXLSX` always returns a frame. Perhaps it needs to take a constructor class/function as an argument?

**Comment by flexatone** [comment]
Thanks for isolating this issue.

This has been corrected, and all similar constructors now also return the appropriate `Frame` subclass. This fix will be available in the 0.5.12 release.
