### ISSUE TITLE
Add reorder_for_hierarchy in more places

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#155]
In #113 we decided to add a `reorder_for_hierarchy` parameter to `Frame.set_index_hierarchy`. I think it would also be useful to add that parameter to `IndexHierarchy.from_labels` (and maybe other constructors). 

The use case is the same; the code to implement a partial reordering that makes an iterable compatible with `IndexHierarchy` is [involved](https://github.com/InvestmentSystems/static-frame/blob/9756acfa847a90a29906112500977fd1005a784a/static_frame/core/container_util.py#L410), especially if you want to preserve the original ordering as much as possible. I expect exposing the parameter in more locations will save StaticFrame users from writing their own, possibly flawed implementations.

**Comment by flexatone** [comment]
Thank you for this suggestion.

I have added the `reorder_for_hierarchy` for Boolean option to `IndexHierarchy.from_labels`. As with other usage of this parameter, the ordering will preserve the observed order of unique values.

This feature will be available in 0.5.12. I will close this issue for now, but feel free to reopen if we find more interfaces that might benefit from the `reorder_for_hierarchy`  option.

```python
>>> labels1 = (('II', 'A', 1),
...                 ('I', 'B', 1),
...                 ('II', 'B', 2),
...                 ('I', 'A', 2),
...                 ('I', 'B', 2),
...                 ('II', 'A', 2),
...                 ('II', 'B', 1),
...                 ('I', 'A', 1),
...                 )
>>> sf.IndexHierarchy.from_labels(labels1, reorder_for_hierarchy=True)
<IndexHierarchy>
II               A        1
II               A        2
II               B        1
II               B        2
I                A        1
I                A        2
I                B        1
I                B        2
<object>         <object> <object>
```
