### ISSUE TITLE
apply() defaults to return key if key is not found when passed a map.

### ISSUE THREAD

**Issue by johnjhawk** [InvestmentSystems/static-frame#156]
example:
```python
>>> f1 = sf.Frame(['I','II','III'], columns=('A',))
<Frame>
<Index> A     <<U1>
<Index>
0       I
1       II
2       III
<int64> <<U3>
>>> f2 = sf.Frame([67,28, 99], columns=('B',),index=('I','II','IV'))
<Frame>
<Index> B       <<U1>
<Index>
I       67
II      28
IV      99
<<U2>   <int64>
>>> f1['A'].iter_element().apply(f2['B'])                                                                                                                                                            
<Series>
<Index>
0        67
1        28
2        III
<int64>  <object>
```

**Comment by flexatone** [comment]
Thank you for posting this issue.

This is, however, the expected behavior at present. That is, given an object used as a mapping in an `apply`, if that object does not have a key for the supplied value, the supplied value remains unchanged. This permits using a partial mapping to change only the values that are found in the mapping.

For more explicit functionality, the user can provide a function that returns the desired value if the key does not match.

**Comment by flexatone** [comment]
Another option is to create a new interface on `IterNodeDelegate` (the object returned by `iter_element()`), called something like `map_intersect`, such that we can have a discrete interface that accepts a `fill_value` argument, and makes clear that we only return values on the intersection of keys. It does not make sense for a general `apply()`  function to take a `fill_value`, as the general case of a `apply()` is applied to all values.

The call above would then look something like this:

```python
>>> f1['A'].iter_element().map_intersect(f2['B'], fill_value=np.nan)
```

What do you think?

**Comment by varkendoug** [comment]
Thanks for the response. I like the map_intersect option, but at that point would it make sense to have separate apply functions. One that takes a function (apply_func) and one that takes a map (apply_map)? Then the fill_value could be an option for apply_map.

**Comment by flexatone** [comment]
Thanks for these suggestions.

I agree that having the `apply` method work with both callables and mapping types is a bit overloaded, and in general we want to favor having discrete methods for such functionality.

However, the current functionality that `apply` provides with mapping types cannot be easily offered with a function that exposes a `fill_value`, as it becomes awkward to distinguish between a value for filling (such as `None` or `nan`) and a parameter to indicate no filling (i.e., if the map does not have a key, retain the original value).

Thus, `IterNodeDelegate` might have three functions:

1. `apply(callable)`: given a callable, return a value for each value iterated
2. `map_fill(mapping, fill_value=np.nan)`: given a mapping type, return the value when the key matches, else use `fill_value`.
3. `map_available(mapping)`: given a mapping type, return the value when the key matches, else return the original value.

While I think having three discrete functions makes sense, I am unsure of the naming for (2) and (3). The term `apply_map` feels a little redundant to me, as both "apply" and "map" are used to refer to function application across a series of values. Suggestions are welcome!

**Comment by flexatone** [comment]
StaticFrame 0.5.12 will deprecate using mappings in `apply` calls and offers three specialized alternatives: `map_any` (formerly suggested as `map_available`), `map_all`, and `map_fill`. Examples follow:

```python
>>> s = sf.Series((10, 20), index=('a', 'b'))
>>> s
<Series>
<Index>
a        10
b        20
<<U1>    <int64>

>>> s.iter_element().map_any({10: 1000})
<Series>
<Index>
a        1000
b        20
<<U1>    <int64>

>>> s.iter_element().map_fill({10: 1000}, fill_value=np.nan)
<Series>
<Index>
a        1000.0
b        nan
<<U1>    <float64>

>>> s.iter_element().map_all({10: 1000})
Traceback (most recent call last):
KeyError: 20

>>> s.iter_element().map_all({10: 1000, 20: 2000})
<Series>
<Index>
a        1000
b        2000
<<U1>    <int64>
```
