### ISSUE TITLE
Series.to_dict(), Frame.to_dict(), Index.to_dict()

### ISSUE THREAD

**Issue by flexatone** [InvestmentSystems/static-frame#157]

**Comment by brandtbucher** [comment]
`dict(series)`, `dict(frame)`, `{**series}`, and `{**frame}` already work. Would the behavior of `to_dict` be any different?

Is the desired behavior of `index.to_dict()` the same as `dict(index.items())`? I think it's a bit interesting that `Index.__getitem__` doesn't accept the keys given by `Index.keys` or `Index.__iter__`. Otherwise it would "just work", too!

**Comment by flexatone** [comment]
Great observations. Let me think about it. 

`Index` is a little odd in the ways you point out, but this is because of how it is used as a mapping in `Series` and `Frame`. Having `to_dict` on `Index` is not likely very useful, so we can drop that one immediately!

**Comment by brandtbucher** [comment]
I think `Index` is more like a sequence with `keys`/`items` methods (and a `values` attribute, but that's a separate discussion). If `__getitem__` took keys and returned values, it would make sense, but it takes integers/slices and returns contained objects, like a sequence (not a mapping).

Related, are `Index.keys`/`Index.items` actually used anywhere? If not, it may make more sense to drop them and ignore the temptation to make it mapping-ish at all...

**Comment by flexatone** [comment]
Thanks again for these points.

Agreed: there is no need for `to_dict()` methods on `Frame` and `Series`, as direct `dict` construction works perfectly.

Your observations on the `Index` are valuable. I have removed `keys()` and `items()` methods from `Index` and `IndexHierarchy`. For the latter, this permitted removing some of that containers cached/managed state, simplifying the implementation and likely increasing performance by some small bit.

Now, when trying to create a `dict` from a `Index`, we get the following error, which seems like the right error to get when trying to create a `dict` from something that is not dict like.

```python
>>> dict(sf.Index(['a', 'b', 'c']))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```
