### ISSUE TITLE
Limited number of values examined when inducing dytpe from untyped data

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#158]
It looks like StaticFrame doesn't inspect all types when consuming an iterable, and as a result sometimes makes the wrong decision. `sf.Series(tuple('asdf' for i in range(10)) + tuple(float('nan') for i in range(10)))` generates a series of strings, where the `nan`s have been coerced to `'nan'`.

I assume this stems from [resolve_type_iter](https://github.com/InvestmentSystems/static-frame/blob/master/static_frame/core/util.py#L696) only taking a sample of the data to determine dtype.

This causes surprising results when adding a column to a FrameGO:

```python
f = sf.FrameGO(index=range(20))
f['mixed_nans'] = tuple('asdf' for i in range(10)) + tuple(float('nan') for i in range(10))
f.iloc[-1, -1] # returns 'nan'
```

**Comment by flexatone** [comment]
Thanks for posting this issue.

At present, this is expected behavior.

When bringing in untyped data into containers, it is necessary to intervene in default array construction and try to get more compatible types. However, this intervention is expensive, and we just limit it to a sample of the data, presently set to 10 values. Thus, you can show the same as above with the following:

```python
>>> sf.Series(tuple('asdf' for i in range(9)) + (np.nan,))[-1]
nan
>>> sf.Series(tuple('asdf' for i in range(10)) + (np.nan,))[-1]
'nan'
```
Of course, we are trying to do better than NumPy alone, which does the following:

```python
>>> np.array(['nan', np.nan])
array(['nan', 'nan'], dtype='<U3'
```
The performance cost of searching all values in all untyped containers, instead of a sampling of values, is probably unreasonably expensive. The very practical alternative is for the caller to provide typed data, i.e.:

```python
>>> f = sf.FrameGO(index=range(20))
>>> f['mixed_nans'] = np.array(tuple('asdf' for i in range(10)) + tuple(float('nan') for i in range(10)), dtype=object)
>>> f.iloc[-1, -1]
nan
```
Of course, we could reject untyped containers in all such moves, but that also seems unreasonable. 

Would you suggest a different approach?

**Comment by ForeverWintr** [comment]
Yes, I think a different approach is preferable. I'll try to explain why.

IMO, a library should have priorities in this order:

1. Safety 
2. Usability
3. Performance

I think correctly determining the dtype for untyped data falls under item 1. Consider how easily a StaticFrame user could introduce bugs by relying on SF's type inspection, especially if they develop on a small 'representative' dataset. You could also argue that type inspection relates to item 2, as a SF user may not *know* the dtype of the untyped data they have, and correctly choosing a dtype is complex.

Currently, I think SF is prioritizing Performance over Usability and Safety, and I think this is a mistake.

I also think comparison to numpy shouldn't apply here. Numpy fills a different use case and has a general expectation about uniform dtypes in an array. SF and its users do not have this expectation, and using `nan` for missing data means that mixed types are common.

__________

Based on the above, I suggest reorienting SF's type inspection to prioritize safety and usability over performance. Instead of doing limited dtype inspection by default, do full dtype inspection *unless a dtype is provided*. By doing this:

- Users can rely on getting the correct dtypes by default (safety).
- Users who do not know the dtype of their data can let SF determine it for them (usability).
- Users who need performance can pass a dtype explicitly, in which case SF can skip its dtype check (performance).

**Comment by ForeverWintr** [comment]
Note that it's also possible to stumble on this without having access to underlying untyped data at all. e.g.:

```python
f['mixed_nans'].iter_element().apply({})
```

The above produces a new Series where `nan`s have been converted to string. `apply` takes a dtype argument, but without access to the intermediate iterable, I think it will be difficult for a user to determine the correct dtype to provide.

**Comment by flexatone** [comment]
Thank you for clearly and persuasively presenting your position. I agree, and have made the change: as part of the 0.5.13 release, all untyped iterables will be fully examined for type resolution. In addition, `Frame.from_records` and related routines will now (in the absence of given dtypes) also do full type resolution.

```python
>>> f = sf.FrameGO(index=range(20))
>>> f['mixed_nans'] = tuple('asdf' for i in range(10)) + tuple(float('nan') for i in range(10))
>>> f.iloc[-1, -1]
nan
```
