### ISSUE TITLE
Don't take arbitrary args and kwargs in iter_group.

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#168]
The [docs for Series.iter_group](https://static-frame.readthedocs.io/en/latest/api_iter.html#Series.iter_group) suggest it takes a `key` argument, and at first glance it appears to:

```python
b = sf.Series([1, 2, 3])
grouper = b.iter_group(5)
```

However the resulting object fails if you try to use it:

```python
next(iter(grouper)) # builtins.TypeError: _axis_group() takes 1 positional argument but 2 were given
```

In fact, it turns out that `iter_group` takes arbitrary args and kwargs on both `Series` and `Frame`:

```python
a = sf.Frame.from_elements([1, 2, 3])
intelligent_grouper = a.iter_group(use_ai=True)
evil_grouper = b.iter_group(destroy_world=True)
```

I suggest wrapping the underlying `iter_group` in Frame and Series specific methods that expose an interface specific to each, to make interface inspection easier.

**Comment by flexatone** [comment]
Many thanks for isolating this issue.

The initial implementation of these interfaces were using a common, unspecialized `__call__` method that simply did full delegation to the actual implementation method. I was able to replace these with derived interfaces, specializing `__call__` for each interface type, and in so doing explicitly define the expected args and kwargs.

With this change all of your examples above raise the expected exception. This will be part of the 0.6.1 release.

```python
>>> s = sf.Series([1, 2, 3, 2, 3])

>>> s.iter_group(use_ai=True)
Traceback (most recent call last):
TypeError: __call__() got an unexpected keyword argument 'use_ai'
>>> s.iter_group(destroy_world=True)
Traceback (most recent call last):
TypeError: __call__() got an unexpected keyword argument 'destroy_world'
>>> s.iter_group(5)
Traceback (most recent call last):
TypeError: __call__() takes 1 positional argument but 2 were given

>>> [x.values.tolist() for x in s.iter_group()]
[[1], [2, 2], [3, 3]
```
