### ISSUE TITLE
sort_index() doesn't preserve index name

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#172]
```python
a=sf.Frame.from_elements(range(3), index=sf.Index(range(3), name='asdf')).sort_index()
a.index.name # None
```

The same happens with `Series`.

From looking at [the code](https://github.com/InvestmentSystems/static-frame/blob/e698a501557de39d44657791a114750db5799e22/static_frame/core/frame.py#L3560), it seems sorting the index results in constructing a new index using `Index.from_labels`.  Is there a potential optimization here if `sort_index` constructs the new index itself, assigning name and dtype and potentially preventing the frame constructor from having to do dtype inference?

**Comment by flexatone** [comment]
Thank you for isolating this issue!

As you suggest, the optimal way to handle this is to create the `IndexBase` object in the outer-most container method. We do not need to pass dtype, as the NP array given to `from_labels` will carry its dtype and not require type inference down-stream.

This is implemented for `Series.sort_index`, `Series.sort_values`, `Frame.sort_index`, `Frame.sort_columns`, and `Frame.sort_values`, and will be available in 0.6.1

Your example now works as expected:

```python
>>> a = sf.Frame.from_elements(range(3), index=sf.Index(range(3), name='asdf')).sort_index()
>>> a.index.name
'asdf'
```
