### ISSUE TITLE
Feature Request: Build Frame from `iter_array` iterators

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/static-frame#173]
When running the following code
```
f = sf.Frame.from_records(np.arange(9).reshape(3,3))
f.iter_array(axis=1).apply(lambda x: x)
```
it raises the following error:
`ErrorInitSeries: dimensionality of final values not supported`

I can only supply a callable that does not return a numpy array. I would really like the ability to call this function, where it can build either a Series or a Frame depending on the return type of the callable.

**Comment by flexatone** [comment]
Thank you for posting this issue.

Function application on a `Frame` always returns a `Series`, as determining when the result should be a `Series` or a `Frame`, based on the output of the function given to `apply`, is very problematic. For example, a user might want a `Series` of tuples, or a `Frame`; and if a `Frame`, it is not clear what the column/index names should be. 

Instead, in such cases, the `apply_iter` or `apply_iter_items` methods can be used to feed a `Frame` constructor, where the user can then provide exactly the column/index labels needed. 

For example:
```python
>>> f = sf.Frame.from_records(np.arange(9).reshape(3,3))
>>> sf.Frame.from_records(f.iter_array(axis=1).apply_iter(lambda x: (x[0] + x[1], x[2])), columns=('a', 'b'))
<Frame>
<Index> a       b       <<U1>
<Index>
0       1       2
1       7       5
2       13      8
<int64> <int64> <int64>
```
