### ISSUE TITLE
Reduce size of huge autoincremented Index objects.

### ISSUE THREAD

**Issue by brandtbucher** [InvestmentSystems/static-frame#181]
Creating a `sf.Index(range(100_000_000))` results in a 5GB `dict` object being created and filled with `{0: 0, 1: 1, 2: 2, 3: 3, ...}`.

SF should handle this case better, and skip the map entirely. This should result in big wins for speed and memory.

**Comment by flexatone** [comment]
Many thanks for posting this issue. 

The optimization you suggest makes sense, and also permits removing the internal `_loc_is_iloc` Boolean, as the presence of `_map` can be used to determine the same. This change will be available the 0.6.2 release.

Now, the following Index has no `_map`, and consumes far fewer resources.

```python
>>> index = sf.Index(range(100_000_000), loc_is_iloc=True)
>>> index._map is None
True
```

**Comment by brandtbucher** [comment]
Is it necessary to pass `loc_is_iloc` to get this optimization?

**Comment by flexatone** [comment]
If you are explicitly creating the Index, then yes, passing `loc_is_iloc` is required, but in cases where you generally want an auto-incremented integer index, you get this automatically by setting the `index` and/or `columns` parameter to `None` or `sf.IndexAutoFactory`. In general, `loc_is_iloc` is considered a "private" parameter for internal usage.

```
>>> f = sf.Frame.from_records([[1, 10], [2, 20]])
>>> f.index._map
>>> f.columns._map
```
It sounds like you are suggesting automatically discovering if an `Index`, created with contiguous ascending integers that start at 0, can use the `loc_is_iloc` configuration. I considered this, but figured it would be rather expensive, and also that most cases where those indices are created, the user has provided `None` or `sf.IndexAutoFactory` explicitly.

Can you elaborate on how you are getting a no auto incremented integer `Index`?

**Comment by brandtbucher** [comment]
I am using `Frame.from_pandas`. Something like:

```py
>>> df = pd.read_csv(huge_file, sep="\t", parse_dates=date_columns, usecols=columns)
>>> f = sf.Frame.from_pandas(df)
>>> type(f.index._map)
<class 'dict'>
>>> sys.getsizeof(f.index._map)
5368709224

```

**Comment by flexatone** [comment]
The solution then is to support `index_constructor` and `columns_constructor` parameters in `Frame.from_pandas`, which we need for other reasons; I just added an issue for that and will prioritize that feature and a release.

In the mean time, you could manually create your `Frame` by doing something like this:

```python
>>> df = pd.DataFrame.from_records([[1, 10], [2, 20]])
>>> f = sf.Frame.from_items((k, v.values) for k, v in df.items())
>>> f.index._map == None
True
```
