### ISSUE TITLE
String concatenation fails on series with U{n} dtypes

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/static-frame#194]
I discovered that series with dtype `U{n}` will not allow string concatenation

```python
>>> s = sf.Series.from_element('a', index=range(3), dtype='U2')
>>> s
<Series>
<Index>
0        a
1        a
2        a
<int64>  <<U2>

>>> s + '_'
UFuncTypeError                            Traceback (most recent call last)
...
...
UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U2'), dtype('<U2')) -> dtype('<U2')
```
But series with dtype `object` will:
```python
>>> s = sf.Series.from_element('a', index=range(3), dtype=object)
>>> s + '_'
<Series>
<Index>
0        a_
1        a_
2        a_
<int64>  <object>
```
Further investigation shows that numpy raises this exact same error when trying to perform the same concatenation:
```python
>>> arr = np.array(['a','a','a'], dtype='U2')
>>> arr + '_'
...
...
UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U2'), dtype('<U2')) -> dtype('<U2')
```
But using this specific numpy string api will:
```python
>>> np.char.add(arr, '_')
array(['a_', 'a_', 'a_'], dtype='<U3')
```
Or alternatively, using the `+` operator to perform string concatenation on arrays with dtype `object`:
```python
>>> arr = np.array(['a','a','a'], dtype=object)
>>> arr + '_'
array(['a_', 'a_', 'a_'], dtype=object)
```

From what I gathered, there is an entire suite of string methods numpy intends its users to apply for string operations: https://docs.scipy.org/doc/numpy/reference/routines.char.html. At the very least, appending strings to series with dtype `U{n}` should not fail.

**Comment by flexatone** [comment]
Thank you for posting this issue. Support for these string operations has been implemented for all containers. This will be made available as part of the 0.6.17 release.

```python
>>> s = sf.Series.from_element('a', index=range(3), dtype='U2')
>>> s + '_'
<Series>
<Index>
0        a_
1        a_
2        a_
<int64>  <<U3>
```
