### ISSUE TITLE
DisplayConfig: An option to drop index during display

### ISSUE THREAD

**Issue by gdevanla** [InvestmentSystems/static-frame#204]
It would be nice if we could have an option to `hide` the index during display (both on console and with other rendering functions like `to_html()`). Probably, this can be extended to column display as well.

**Comment by flexatone** [comment]
Many thanks for posting this issue! I had, however, just created nearly the same (#201), so we can can mark this as duplicate.

**Comment by gdevanla** [comment]
Thanks. Sorry did not notice the earlier  entry that was created for this issue.
