### ISSUE TITLE
Silent Truncation When Writing Large Excel Files

### ISSUE THREAD

**Issue by brandtbucher** [InvestmentSystems/static-frame#209]
The XLSX format is limited to `2**20` rows and `2**14` columns.  Calling `Frame.to_xlsx` will "successfully" write a `Frame` of any size by silently dropping all data outside of this range.

We should raise here, instead. Some care will need to be taken to consider space taken up by the index and columns when figuring out if the data exceeds these limits.

There are some [other practical limits](https://support.office.com/en-us/article/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3) as well (`2**15-1` characters and `2**8-3` line breaks per cell, for example), but these are much more expensive to check and will rarely be encountered in practice.

**Comment by flexatone** [comment]
Many thanks for posting this issue.

I agree a pre-check here makes sense, and including columns / index depth will not be a problem.

While I can confirm the truncation of rows at 1,048,576, I see columns (on `libreoffice --calc`) truncated at 1024. An Excel-using colleague confirmed that he could load the expected 16,384 columns.

I assume we should fail at the documented constraint, and assume that LibreOffice will catch up.

**Comment by flexatone** [comment]
This check is now in place and will be part of the 0.6.16 release.

This example shows that at the boundary of rows, the presence of the columns (as row) makes the difference for the data to fit.

```
>>> f1 = sf.Frame.from_element('x', index=range(1048576), columns='x')
>>> f1.to_xlsx('/tmp/test.xlsx')
RuntimeError: Frame rows do not fit into XLSX sheet (1048577 > 1048576)

>>> f1.to_xlsx('/tmp/test.xlsx', include_columns=False)
```
