### ISSUE TITLE
Enums are casted to strings if they inherit from `str`

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/static-frame#210]
I have observed some interesting static-frame behavior as it relates to Enums and Enum/str mixin classes. See below:
```python
>>> from enum import Enum
>>> class Foo(Enum): 
    ...:     a='a' 
    ...:     b='b' 
    ...:

>>> sf.Series([Foo.a, Foo.b])
'''
<Series>
<Index>
0        Foo.a
1        Foo.b
<int64>  <object>
'''
>>> sf.Index([Foo.a, Foo.b])
'''
<Index>
Foo.a
Foo.b
<object>
'''
>>> sf.Frame.from_records([[Foo.a, Foo.b]])
'''
<Frame>
<Index> 0        1        <int64>
<Index>
0       Foo.a    Foo.b
<int64> <object> <object>
'''
>>> class Bar(str, Enum): 
    ...:     a='a' 
    ...:     b='b' 
    ...:

>>> sf.Series([Bar.a, Bar.b])
'''
<Series>
<Index>
0        B
1        B
<int64>  <<U1>
'''

>>> sf.Index([Bar.a, Bar.b])
'''
<Index>
B
B
<<U1>
'''
>>> sf.Frame.from_records([[Bar.a, Bar.b]])
'''
<Frame>
<Index> 0     1     <int64>
<Index>
0       B     B
<int64> <<U1> <<U1>
'''

>>> sf.Frame.from_records([[Foo.a, Bar.b]])
15:53:49 Out [20] 
'''
<Frame>
<Index> 0        1     <int64>
<Index>
0       Foo.a    B
<int64> <object> <<U1>
'''
```

As you can see, for Frames, Series, and Indices, Enum's are casted to strings when the Enum has `str` as a mixin, otherwise they are left as enum objects.

I am not sure if this is a good default behavior, as all information about the Enum is lost once it's casted to `str`. I think the default behavior should be to leave Enums alone, and have the user call `.astype(str)` if they want that behavior. I'm open to a different opinion on this.

**Comment by flexatone** [comment]
Many thanks for posting this issue.

Explicit handling for multiple-inherited `Enum` types is now implemented. As `Enum`-derived classes are iterable, they can also be used in `Series` or `Index` construction.

This will be made available in the 0.6.17 release.

```python
>>> from enum import Enum
>>> class Bar(str, Enum):
...     a = 'a'
...     b = 'b'
...     c = 'c'
... 
>>> s1 = sf.Series(Bar, index=Bar)
>>> s1
<Series>
<Index>
Bar.a    Bar.a
Bar.b    Bar.b
Bar.c    Bar.c
<object> <object>
>>> s1.loc[[Bar.a, Bar.c]]
<Series>
<Index>
Bar.a    Bar.a
Bar.c    Bar.c
<object> <object>
```
