### ISSUE TITLE
Frame.from_parquet error with columns_depth=2

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#211]
I'm unable to load a frame with hierarchical columns from a parquet file:

```python
f = sf.FrameGO.from_element('a', index=range(3), columns=sf.IndexHierarchy.from_labels((('a', 'b'),)))
f.to_parquet('/tmp/tmp.pq')
sf.Frame.from_parquet('/tmp/tmp.pq', columns_depth=2)

# ValueError: malformed node or string: <_ast.Name object at 0x7f1af1e85490>
```
I think the cause may be that I'm not passing index_depth=1, and static frame is attempting to `literal_eval` `'__index__0'`. However, If I repeat the same with index_depth=1 I get

```SyntaxError: EOL while scanning string literal```

**Comment by flexatone** [comment]
Many thanks for posting this issue.

While I can reproduce the error when `index_depth` is not provided, when `index_depth=1`, I do not observe a failure.

```
>>> f = sf.FrameGO.from_element('a', index=range(3), columns=sf.IndexHierarchy.from_labels((('a', 'b'),)))
>>> f.to_parquet('/tmp/tmp.pq')
>>> sf.Frame.from_parquet('/tmp/tmp.pq', columns_depth=2, index_depth=1)
<Frame>
<IndexHierarchy> a        <<U1>
                 b        <<U1>
<Index>
0                a
1                a
2                a
<int64>          <object>
```
That said, more robust handling for the case of an auto-created index-label being interpreted as an IndexHierarchy might be possible. Or at least we can provide a better error message.

**Comment by flexatone** [comment]
I think the  best thing to do in this case is to fail, rather than try to make-up hierarchical levels for a field that is not encoded as hierarchical. I have identified these cases, and now provide a better exception. Again, the best way to get past this is to provide the expected `index_depth`.

```python
>>> f = sf.FrameGO.from_element('a', index=range(3), columns=sf.IndexHierarchy.from_labels((('a', 'b'),)))
>>> f.to_parquet('/tmp/tmp.pq')

>>> sf.Frame.from_parquet('/tmp/tmp.pq', columns_depth=2, index_depth=1)
<Frame>
<IndexHierarchy> a        <<U1>
                 b        <<U1>
<Index>
0                a
1                a
2                a
<int64>          <object>

>>> sf.Frame.from_parquet('/tmp/tmp.pq', columns_depth=2, index_depth=0)
Traceback (most recent call last):
RuntimeError: Could not parse more than one label from delimited string: __index0__
```
