### ISSUE TITLE
Frame.from_concat drops index names

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#219]
The docstring for `Frame.from_concat` says

> If the axis along concatenation (index for axis 0, columns for axis 1) is unique after concatenation, it will be preserved;

However, although the values are preserved, the index name is not:

```python
frames = tuple(sf.Frame.from_element(1, index=sf.Index([i], name='tom'), columns=[str(i)]) for i in range(2, 4))

sf.Frame.from_concat(frames, axis=1)
<Frame>
<Index> 2         3         <<U1>
<Index>
2       1.0       nan
3       nan       1.0
<int64> <float64> <float64>
sf.Frame.from_concat(frames)
<Frame>
<Index> 2         3         <<U1>
<Index>
2       1.0       nan
3       nan       1.0
<int64> <float64> <float64>
```
I think index name should be preserved here too. Thoughts?

**Comment by flexatone** [comment]
Thanks for isolating this issue. This exposed a few shortcomings in how indices are handled in `Frame.from_concat`. Now, if fully aligned for indices on the same axis, names, index type, and contained index types within IndexHierarchy are all preserved. This relates to #217. This will be made available as part of the 0.6.21 release.

```python
>>> frames = tuple(sf.Frame.from_element(1, index=sf.Index([i], name='tom'), columns=[str(i)]) for i in range(2, 4))
>>> sf.Frame.from_concat(frames, axis=1)
<Frame>
<Index>      2         3         <<U1>
<Index: tom>
2            1.0       nan
3            nan       1.0
<int64>      <float64> <float64>
```
