### ISSUE TITLE
Regex filtering

### ISSUE THREAD

**Issue by Rockwell70** [InvestmentSystems/static-frame#226]
I'm a new static-frame user and I have a pandas script that filters a dataframe based on the following regex filter:

ee = ee[ee['Job Title'].str.contains("biomedical|RN|diet|clinical admin|ccht", case=False, regex=True) == True]

I'm trying to recreate this in static-frame but with no luck. Is this possible yet in static-frame?

**Comment by flexatone** [comment]
Thank you for your question!

StaticFrame exposes a number of string methods by way of the `via_str` accesors:
https://static-frame.readthedocs.io/en/latest/api_overview.html#api-overview-series-accessor-string

These are implemented with NumPy's string methods: 
https://numpy.org/doc/stable/reference/routines.char.html

While Pandas provides `Series.str.contains()` and `Series.str.match()` methods, NumPy does not provide similar methods, and it appears that Pandas implementation is essentially elementwise application of `re.match` on the `Series`. For those reasons, SaticFrame has not implemented such methods, letting users simply use `re.match` with existing tools for function application. For example:

```python
>>> import re
>>> s = sf.Series(('foo', 'BAR', 'baz'))
>>> s.iter_element().apply(lambda e: bool(re.match('foo|bar', e, re.IGNORECASE)))
<Series>
<Index>
0        True
1        True
2        False
<int64>  <bool>
```
This is admittedly more verbose, but likely has the same performance, and gives the user full control in using the `re` module. In the future, if there is broad interest, `re` functionality might be exposed in a custom StaticFrame interface.

**Comment by Rockwell70** [comment]
Thanks for the quick response and explanation, which makes complete sense.

Cheers,
J

**Comment by flexatone** [comment]
I will close this ticket for now, but if others are interested in `re` interfaces in StaticFrame, this ticket can be re-opened.
