### ISSUE TITLE
`sf.Frame.pivot` performance issues: Round 2

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/static-frame#244]
I came across another case where `sf.Frame.pivot` is extremely slow to use, forcing a temporary conversion to pandas & back.

The use case came when attempting to pivot an extremely tall frame (~1 mil records), and so I have derived the following example code as it is closely representative of the real-world use case where I originally came across the performance issue.

Setup
```python
import static_frame as sf
import numpy as np

groups = np.arange(75_000)

size_map = { 5:  5_000,
             6:  7_500,
             7:  1_000,
             8: 10_000,
             9: 10_000,
            10: 15_625,
            15:  5_000,
            20: 10_000,
            25:  6_250,
            50:  4_625}

group_sizes = []
for k, v in size_map.items():
    group_sizes.extend([k] * v)

assert len(groups) == len(group_sizes)

def gen_group_values():
    for group in groups:
        yield np.full(group_sizes[group], group)

def gen_group_unique_values():
    for group in groups:
        yield np.arange(group_sizes[group])


group_values = sf.Series(np.concatenate(list(gen_group_values())), name='group')
group_unique_values = sf.Series(np.concatenate(list(gen_group_unique_values())), name='group_unique')
value_values = sf.Series(np.random.random(len(group_values)), name='data')

frame = sf.Frame.from_concat((group_values, group_unique_values, value_values), axis=1)

print(frame.shape) # (1065750, 3)
```

This call takes ~9 mins
```python
frame.pivot(index_fields='group_unique', columns_fields='group', data_fields='data')
```

This call takes (minus the pandas conversion) ~1 sec
```python
df = frame.to_pandas()
df.pivot(index='group_unique', columns='group', values='data') 
```

**Comment by flexatone** [comment]
Many thanks for isolating this issue. 

While I have not been able to get the performance of this to be less than 1 second, I have been able to reduce it almost two orders of magnitude, to under 15 seconds on my machine. Some of the generality in the original implementation could be reduced to provide more optimized execution.

Further general SF optimization is planned for the future, but for now I will close this issue.
