### ISSUE TITLE
Frame.from_xlsx reads None columns from xlsx with formatting artifacts. 

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#252]
AKA [bad_sheet.xlsx](https://github.com/InvestmentSystems/static-frame/files/5270270/bad_sheet.xlsx) redux.

Similar to #146, but in columns instead of rows, the attached xlsx has formatting applied to the columns to the right of those containing actual data. This causes `Frame.from_xlsx` to fail, because it tries to use the `None`s returned by openpyxl for each column as headers:

```
>>> sf.Frame.from_xlsx('/tmp/bad_sheet.xlsx')
  File "/home/rutherford/.env38/lib/python3.8/site-packages/static_frame/core/frame.py", line 1812, in from_xlsx
    return st.read(label,
  File "/home/rutherford/.env38/lib/python3.8/site-packages/static_frame/core/store.py", line 365, in wrapper
    return f(self, *args, **kwargs) # type: ignore
  File "/home/rutherford/.env38/lib/python3.8/site-packages/static_frame/core/store_xlsx.py", line 505, in read
    columns = container_type._COLUMNS_CONSTRUCTOR(
  File "/home/rutherford/.env38/lib/python3.8/site-packages/static_frame/core/index.py", line 468, in __init__
    raise ErrorInitIndexNonUnique(
static_frame.core.exception.ErrorInitIndexNonUnique: labels (10) have non-unique values (7)
```

**Comment by flexatone** [comment]
Thank you for isolating this case.

Unfortunately, I cannot yet find an efficient way to automatically detect such scenarios. While we can observe trailing `None`s in each row, we would need to evaluate that all rows have the same number of trailing `None`s (requiring a conditional reverse iteration of each row) before then iterating again over all rows, extracting the non-`None` values from each row. As the data from `openpyxl` comes in by row rather than column, this would be very expensive.

A simple workaround in this case, assuming you know how many columns you are expecting, is to load the data with zero `columns_depth`, then create a new `Frame`, extracting just the necessary data and columns labels.

```python
>>> f = sf.Frame.from_xlsx('/tmp/bad_sheet.xlsx', columns_depth=0)
>>> f
<Frame>
<Index> 0     1            2       3      4        5     6        7        8        9        <int64>
<Index>
0       code  display name product region size     Type  None     None     None     None
1       asdf  asdf         fff     dfd    200      adsf  None     None     None     None
2       fdfd  asdf         fff     dfd    200      adsf  None     None     None     None
3       ahah  asdf         fff     dfd    200      adsf  None     None     None     None
4       ddfh  asdf         fff     dfd    200      adsf  None     None     None     None
5       hdf   asdf         fff     dfd    200      adsf  None     None     None     None
<int64> <<U4> <<U12>       <<U7>   <<U6>  <object> <<U4> <object> <object> <object> <object>

>>> sf.Frame(f.iloc[1:, :6], columns=f.iloc[0, :6])
<Frame>
<Index> code  display name product region size     Type  <object>
<Index>
1       asdf  asdf         fff     dfd    200      adsf
2       fdfd  asdf         fff     dfd    200      adsf
3       ahah  asdf         fff     dfd    200      adsf
4       ddfh  asdf         fff     dfd    200      adsf
5       hdf   asdf         fff     dfd    200      adsf
<int64> <<U4> <<U12>       <<U7>   <<U6>  <object> <<U4>
```

The only other option I can see is making this potentially very expensive trimming optional with a new parameter. Or, find a way to make `openpyxl` behave more like the deprecated `xlrd` package. With `xlrd`, we do not loads those empty cells.

```python
>>> xlrd.open_workbook('/tmp/bad_sheet.xlsx').sheet_by_index(0).row(0)
[text:'code', text:'display name', text:'product', text:'region', text:'size', text:'Type']
```

**Comment by flexatone** [comment]
A recent SO post on this very issue:
https://stackoverflow.com/questions/64144244/openpyxl-ignoring-cells-that-have-style-but-have-no-values

**Comment by flexatone** [comment]
I have implemented a solution that handles both empty/all-style rows and columns in the outer regions of a table. It is expensive, but implemented with a Boolean mask array, the performance is acceptable. As the cost of performing this check will have to always be paid, even if a table does not contain these empty/all-style rows/columns, we will parameterize it under the parameter  / `StoreConfig` name `trim_nadir`. For backwards compatibility with 0.6.*, the default will be `True`; however, in 0.7.*, we will set the default to `False`.

This change will be part of the 0.6.36 release.

The supplied bad sheet can now  be loaded as expected.

```python
>>> fp = '/tmp/bad_sheet.xlsx'
>>> sf.Frame.from_xlsx(fp)
<Frame>
<Index> code  display name product region size    Type  <<U12>
<Index>
0       asdf  asdf         fff     dfd    200     adsf
1       fdfd  asdf         fff     dfd    200     adsf
2       ahah  asdf         fff     dfd    200     adsf
3       ddfh  asdf         fff     dfd    200     adsf
4       hdf   asdf         fff     dfd    200     adsf
<int64> <<U4> <<U4>        <<U3>   <<U3>  <int64> <<U4>
```
