### ISSUE TITLE
NaN Frame to pandas is slow for large frames

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/static-frame#253]
```python
frame = sf.Frame.from_element(np.nan, index=range(75), columns=range(75000))

df = frame.to_pandas() # This takes ~2 mins

# As juxtaposed to..

df = pd.DataFrame(frame.values, index=frame.index, columns=frame.columns) # Almost instant

**Comment by flexatone** [comment]
Thanks for posting this. Note that here you are passing SF's array to the DataFrame constructor: Pandas does not make a copy of arrays passed this way, leading to the ability to mutate the array (if it is mutable) and have that mutation reflected in the DataFrame.

Further, if you try to do any operations with the DataFrame, it will likely fail, as Pandas does not support immutable arrays.

Anticipating these issues, `to_pandas()` must make copy of the `Frame`'s arrays before passing them to Pandas, likely accounting for all of the overhead you see.

It would be useful to confirm, however, that the time it takes to copy this array makes up the bulk of the observed time seen in `to_pandas`.

**Comment by chaburkland** [comment]
I don't think there is any overhead in copying. `frame.values.copy()` happens nearly instantly. It seems like there is something else going on under the hood the could be optimized.

```python
df = pd.DataFrame(frame.values.copy(), index=frame.index.values.copy(), columns=frame.columns.values.copy()) # Almost instant
```

**Comment by flexatone** [comment]
Good point and illustration. I will investigate further!

**Comment by flexatone** [comment]
Many thanks for isolating this issue. 

I was able to reduce the runtime of this operation to "almost instant": there was an optimization available in `Frame.to_pandas` when the `Frame` has a single array managed by `TypeBlocks`. 

There may be other optimizations that reduce column-wise iteration when creating ``pd.DataFrame`` even when we have heterogeneous types: I will continue to explore the options.
