### ISSUE TITLE
Extend sf.Frame.from_pandas to include an optional name argument

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/static-frame#254]
Right now, there are only two ways to create a named `sf.Frame` from a `pd.DataFrame`.

1) Before
```python
df.name = 'my_name' # This is not ideal, since I'm taking advantage of how Pandas doesn't currently regulate __setattr__
frame = sf.Frame.from_pandas(df)
```

2) After
```python
frame = sf.Frame.from_pandas(df).rename('my_name') # Too much work :(
```

I think it would be ideal to align this constructor's inferface with all the other ones, as I believe most (if not all), allow for an optional `name` argument.
```
frame = sf.Frame.from_pandas(df, name='my_name') # :)

**Comment by flexatone** [comment]
Thank you for this suggestion. 

I have added a `name` parameter to both `Frame.from_pandas` and `Series.from_pandas`; this parameter also permits setting the `name` to None, such that a Pandas `name` attribute can be removed.

This feature will be available as part of the 0.6.35 release.

```python
>>> df = pd.DataFrame(np.arange(4).reshape(2, 2))
>>> df.name = 'foo'
>>> sf.Frame.from_pandas(df, name='bar')
<Frame: bar>
<Index>      0       1       <int64>
<Index>
0            0       1
1            2       3
<int64>      <int64> <int64>
```
