### ISSUE TITLE
Frame.from_records constructor does not accept dict_keys/_values as dytpe argument 

### ISSUE THREAD

**Issue by johnjhawk** [InvestmentSystems/static-frame#270]
Hi, 

The Frame.from_records constructor does not accept dict_keys/_values, as they are not subscriptable. For example:
`kv = {'x': None, 'y': None}`

`sf.Frame.from_records(('a','b'), index=kv.keys(), dtypes=kv.values())`
TypeError: 'dict_values' object is not subscriptable

`In [15]: sf.Frame.from_records(('a','b'), index=kv.keys(), dtypes=tuple(kv.values()))`                                                                                              
Work just fine.

This makes sense why non indexable objects fail, but wanted let you know in case you would like to handle it. 

Thanks,
John

**Comment by flexatone** [comment]
Thanks for identifying this issue. Supporting `dict_values` in this context is desirable. This is fixed and will be part of the 0.7.4 release.

```python
>>> kv = {'x': int, 'y': str}
>>> f1 = sf.Frame.from_records([('10', 5), ('3', 20)], columns=kv.keys(), dtypes=kv.values())
>>> f1
<Frame>
<Index> x       y     <<U1>
<Index>
0       10      5
1       3       20
<int64> <int64> <<U2>
```
