### ISSUE TITLE
 to_csv does not quote values that have a comma or quotes

### ISSUE THREAD

**Issue by johnjhawk** [InvestmentSystems/static-frame#274]
to_csv does not quote values that have a comma or quotes
```
In [13]: f = sf.Frame.from_dict({'A': ["a", "a,a", "a,'a',a"]})
In [15]: f.to_csv(out)
In [16]: print(out.read())                                                                    
__index0__,A
0,a
1,a,a
2,a,'a',a
```
I expected the following:
```
__index0__,A
0,a
1,"a,a"
2,"a,'a',a"
```
Thanks,
John

**Comment by flexatone** [comment]
Useful reference to approaching this is the Python CSV module:
https://docs.python.org/3/library/csv.html

This requires at least the introduction of two controls, maybe more:
- `quote_char`: the character to use for quoting
- `double_quote`: if the quote char is found in a cell, it is doubled, else an escape char is raised. if no escape char is being used, can raise

The csv module defines four approaches to quoting when writing (with implications for reading).

csv.QUOTE_ALL

    Instructs writer objects to quote all fields.

csv.QUOTE_MINIMAL

    Instructs writer objects to only quote those fields which contain special characters such as delimiter, quotechar or any of the characters in lineterminator.

csv.QUOTE_NONNUMERIC

    Instructs writer objects to quote all non-numeric fields.
    Instructs the reader to convert all non-quoted fields to type float.

csv.QUOTE_NONE

    Instructs writer objects to never quote fields. When the current delimiter occurs in output data it is preceded by the current escapechar character. If escapechar is not set, the writer will raise Error if any characters that require escaping are encountered.
    Instructs reader to perform no special processing of quote characters.

**Comment by flexatone** [comment]
Thanks for reporting this issue. All delimited file writers have been updated to make use of the standard-libraries `csv` module, which provides robust features for quoting and escaping. All relevant parameters are exposed, and the default configuration does basic quoting, as shown below. This will be part of the 0.8.2 release. 


```python
>>> f = sf.Frame.from_dict({'A': ["a", "a,a", "a,'a',a"]})                                                                         
>>> f.to_csv('/tmp/foo.csv')                                                                                                       
>>> print(open('/tmp/foo.csv').read())                                                                                             
__index0__,A
0,a
1,"a,a"
2,"a,'a',a"
```
