### ISSUE TITLE
Frame.from_parquet segfaults when given None as filepath

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/static-frame#291]
Passing in `None` to `sf.Frame.from_parquet` as the first position argument will create a **segfault**.

This is due to an issue with pyarrow - reported here: https://issues.apache.org/jira/browse/ARROW-10910

**Comment by flexatone** [comment]
Thanks for identifying this issue. SF will now intervene be before the call to pyarrow and raise a `ValueError`. This will be part of the 0.7.9 release.
