### ISSUE TITLE
Optimized support for loading multiple labels from a zip parquet store

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/static-frame#292]
I am working with a very large zip parquet store (almost 250,000 items!). I have loaded it into a `sf.Bus`.

However, retrieving frames from the bus is very slow. I have a subset of around 10,000 frames I want to load, but it is taking 1-2 seconds per frame load. I modified my code to retrieve labels multi-key index, although that takes almost exactly as long as retrieving each key individually.

Investigating further, it appears that the actual load from the store is throttled to one label at a time. I think in reasonable cases this isn't an issue, but as the zip parquet store gets larger, there is more and more overhead introduced by the OS in order to "unzip" the store, reach in and pull out the file being loaded, thus leading to the slow load times.

For now, my workaround is to manually unzip my `store.parquet.zip` file, and then load the 10,000 frames I want using `.from_parquet`, and it is orders of magnitude faster.

**Comment by flexatone** [comment]
Many thanks for isolating this issue. The family of `Store` interfaces have been updated to support a `read_many` method that optimizes mutli-Frame reading; `Bus` has been updated to make use of these interfaces. Tests of reading 10,000 `Frame` from a zip parquet show nearly an order-of-magnitude improvement.

This change will be included in the 0.7.14 release.
