### ISSUE TITLE
Generalize connection argument to from_sql

### ISSUE THREAD

**Issue by gdevanla** [InvestmentSystems/static-frame#307]
Currently, `Frame.from_sql` expects a `connection` parameter.  The type of this parameter is set to `sqlite3.Connection`, and the doc string suggests we provide a DBAPI2 (PEP 249) compatible connection object.   The problem with `sqlite3.Connection` object is that, it currently implement the `execute` method which is used in `from_sql`. But, DBAPI, does not specify that the `Connection` object implement the `execute` method. 

Solution:  Since, we want to support DBAPI level `Connection` object, we cannot directly call `execute` on the passed in connection. The alternate approach would be to call the `cursor` method on the `Connection` object and use the `cursor` to fetch the data.

**Comment by flexatone** [comment]
Many thanks for isolating this issue; I will provide more comments in the PR.
