### ISSUE TITLE
Expose dtypes argument to Frame.from_pandas

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/static-frame#309]
I'm hoping that `sf.Frame.from_pandas` can expose a `dtypes` argument.

A very common move that I make, looks like this:

```python
dtypes = {...}
frame = sf.Frame.from_pandas(pd.read_csv(some_fp))
frame = frame.astype(dtypes)
```

Pandas handles dates very differently, and will sometimes do unexpected things when reading from disk. Because of this, I almost always need to sanitize the dtypes, and I'm forced to use an additional line for this.

I think it would be good to expose the parameter, since nearly all other `from_*` constructors expose a `dtypes` argument.

**Comment by flexatone** [comment]
Many thanks for this issue. With 0.8.20, the `dtypes` argument will be available in `Frame.from_pandas()`.
