### ISSUE TITLE
Propagate the name of an Index given to an Index initializer

### ISSUE THREAD

**Issue by brandtbucher** [InvestmentSystems/static-frame#314]
Converting one index type to another should preserve its name. I'd like to do moves like `f.reindex(index=sf.IndexDate(f.index))`, but it seems that I need to do `f.reindex(index=sf.IndexDate(f.index, name=f.index.name))` instead.

**Comment by flexatone** [comment]
Thanks for isolating this issue. This issue was limited to `IndexDatetime` subclasses. This has been corrected and will be part of the 0.8.1 release.
