### ISSUE TITLE
`via_re`: support for applying regular expressions

### ISSUE THREAD

**Issue by flexatone** [InvestmentSystems/static-frame#344]

**Comment by flexatone** [comment]
There are a few approaches to implementing this.

The two main questions are (1) do we want to support the full interfaces on the `Pattern` instances (such as `pos` and `endpos`) and (2) do we want to support the full interface of `Match` objects.

### A. Full Interface
If we say yes to (1) and (2), we might have an interface (on a `Frame`, but similar on other containers), like the following.

First, we expose Pattern methods under a "pattern" namespace and replace `Match` objects with Booleans where appropriate.

```python
Frame.via_re(pattern, flags).pattern.search(pos, endpos) -> bool Frame
Frame.via_re(pattern, flags).pattern.match(pos, endpos) -> bool Frame
Frame.via_re(pattern, flags).pattern.fullmatch(pos, endpos) -> bool Frame
Frame.via_re(pattern, flags).pattern.groups() -> int Frame
Frame.via_re(pattern, flags).pattern.sub(repl, count) -> str Frame
...
```
We then expose `Match` object interfaces under a "match" interface, and then expose `search()`, `match()`, and `fullmatch()` (given as `func` below) that then delegate to `Match` interfaces:

```python
Frame.via_re(pattern, flags).match.func(pos, endpos).group(group) -> str Frame
Frame.via_re(pattern, flags).match.func(pos, endpos).groups(default) -> tuple of str Frame
Frame.via_re(pattern, flags).match.func(pos, endpos).start(group) -> int Frame
...
```
### B. Excluding Match Interfaces, Pattern Creation Isolated
If we say yes to (1) and no to (2), we might have an interface (on a `Frame`, but similar on other containers), like the following.

```python
Frame.via_re(pattern, flags).search(pos, endpos) -> bool Frame
Frame.via_re(pattern, flags).match(pos, endpos) -> bool Frame
Frame.via_re(pattern, flags).fullmatch(pos, endpos) -> bool Frame
Frame.via_re(pattern, flags).groups() -> int Frame
Frame.via_re(pattern, flags).sub(repl, count) -> str Frame
...
```
### C. Excluding Match Interfaces, Pattern Creation Combined
If we say yes to (1) and no to (2), but do not isolated the pattern creation, we might have an interface (on a `Frame`, but similar on other containers), like the following.

```python
Frame.via_re.search(pattern, flags, pos, endpos) -> bool Frame
Frame.via_re.match(pattern, flags, pos, endpos) -> bool Frame
Frame.via_re.fullmatch(pattern, flags, pos, endpos) -> bool Frame
Frame.via_re.groups(pattern, flags) -> int Frame
Frame.via_re.sub(pattern, flags, repl, count) -> str Frame
...
```
Feedback and alternatives are welcome.

**Comment by ForeverWintr** [comment]
Why have `via_re` instead of adding methods to `via_str`? `Frame.via_str.re.match(pattern_or_regex)` is the interface that comes to mind at first thought.

**Comment by flexatone** [comment]
Thanks for this question. One, `via_str` largely represents the methods of `str` objects, or more explicitly the methods found here: (https://numpy.org/doc/stable/reference/routines.char.html); regular expressions are not part of those interfaces. Two, there are many more methods than just `match` and `search` we might expose, so it seems sensible group them under a common namespace.

**Comment by ForeverWintr** [comment]
Interesting. Numpy doesn't have regex methods it seems, but if it did I would expect to find them amongst the other string related routines. Pandas [does this](https://pandas.pydata.org/pandas-docs/stable/reference/series.html#api-series-str), for what it's worth. 

Will `via_re` convert dtypes to `str`, like `via_str` does? If so I think it would be more explicit to make a separate `re` namespace below `via_str`. 

To your second point, `via_str.re` is a common namespace that regex methods can be grouped under, is it not?

**Comment by flexatone** [comment]
Thanks for these points.

Pandas exposes only two regex functions; I am planning on exposing all of them, which is part of having its own name space is attractive.

Yes, `via_re` will convert dtypes to `str`, but I am not sure being under `via_str` is necessary to intuit this: regular expressions only operate on strings.

Finally, `via_str.re` is certainly possible and does achieve its own namespace, but introduces a hierarchy where there was none before, and makes the implementation of `via_*` interfaces less parallel.

As  I get a sample implementation in place I will continue to think about these points.
