### ISSUE TITLE
Extend index auto factories to include size

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/static-frame#346]
**Description**

Right now, `sf.IndexAutoFactory` doesn't provide support for specifying a desired size. This could be particularly helpful when working with large `sf.FrameGO`'s, when the index length is known, but the columns are not realized yet.

**Example**

Provide code or pseudo code demonstrating how the feature might work, or how current behavior might be changed.

```python
fgo = sf.FrameGO(index=sf.IndexAutoFactory(size=100_000_000))

fgo['A'] = create_column_a(...)
fgo['B'] = create_column_b(...)
# etc..
```

This is preferrable to the current behavior, which forces the creation of a temporary throw-away container:
``` python
fgo = sf.FrameGO(index=np.arange(100_000_000)) # Not good! We don't need/want the numpy array
```
**Platform**

Run the following function (static-frame >= 0.8.1) and provide the results to define your platform and environment:

```python
>>> import static_frame as sf
>>> sf.Platform.display()
<Series: platform>
<Index>
platform           Linux-5.4.0-73-generic-x86_64-with-glibc2.27
sys.version        3.8.3 (default, Jun 14 2021, 11:51:22) [GCC 7.5.0]
static-frame       0.8.13
numpy              1.17.4
pandas             0.24.2
xlsxwriter         1.1.2
openpyxl           2.5.4
xarray             <ModuleNotFoundError>
tables             3.6.1
pyarrow            0.17.0
msgpack            <ModuleNotFoundError>
msgpack_numpy      <ModuleNotFoundError>
<<U13>             <object>
```

**Comment by flexatone** [comment]
Many thanks for this suggestion. This is implemented with an interface exactly as you suggested. This will be part of the 0.8.16 release.

```python
>>> f = sf.FrameGO(index=sf.IndexAutoFactory(3))
>>> f.via_fill_value(-1)['a'] = sf.Series((3, 4))
>>> f
<FrameGO>
<IndexGO> a       <<U1>
<Index>
0         3
1         4
2         -1
<int64>   <int64>
```
