### ISSUE TITLE
isfalsy(), notfalsy(), dropfalsy(), fillfalsy()

### ISSUE THREAD

**Issue by flexatone** [InvestmentSystems/static-frame#358]
Family of functions to extend ``isna()``, ``dropna()`` functionality to falsy values, i.e., None, 0, False, and the empty string. For purposes of this functionality, selection will be a super-set of ``isna()``, and thus ``np.nan`` will be treated as falsy (even though it is not).

**Comment by brandtbucher** [comment]
What about `via_bool`?

So `s.isfalsy`, `s.notfalsy()` and `s.dropfalsy()` become `s.via_bool`, `~s.via_bool`, and `s.drop[s.via_bool]`.

**Comment by flexatone** [comment]
@brandtbucher : interesting idea! We loose the opportunity to have the parallelism to the *na() methods, and while your examples are nicely more concise, the via_bool alternative to fillfalsy() would be more verbose. Also, I think we need falsy values more than truthy, so we would more often be inverting via_bool. Still, it is a design worth considering!
