### ISSUE TITLE
`fill_value` to support mappings by column where appropriate

### ISSUE THREAD

**Issue by flexatone** [InvestmentSystems/static-frame#376]

**Comment by flexatone** [comment]
Meets some of the needs of #177.

Proving a mapping by dtype might also meet this need, but would to allow for cases where the same dtype needs different fill values.

**Comment by liangrallc** [comment]
An example. 
fillna for column A with string, fillna for column B with int.

```
f = sf.Frame.from_records(
    (('t', 20, '1954-11'), (np.nan, np.nan, '2020-04')),
    index=sf.IndexYear(('1954', '2020'), name='year'),
    columns=('A', 'B', 'C'),
    name='records',
)
```
