### ISSUE TITLE
Better Handling For Simple Batch Operations

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/static-frame#380]
**Description**

Right now, the Batch internally is built off of (label, containers) iterators, which greatly hinders its relevance to operations that lend themselves to Series outputs.

**Desired Feature**

Consider the simple case of grouping on one column, summing the other, and then getting back a unique summed series.

```python
frame = sf.Frame.from_records([["A", 1.0], ["B", 2.0], ["C", 3.0], ["C", 4.0]], columns=tuple("AB"))
batch = sf.Batch(frame.iter_group_items("A"))["B"].sum()
series = batch.to_series()
<Series>
<Index>
A        1.0
B        2.0
C        7.0
<<U1>    <float64>
```

**Understanding**

Since the above feature is not available, the way to acheive this is to do:
```python
series = batch.to_frame()[None]
```
However, this is sub-optimal, and so the following approach is preferred:
```python
series = frame.iter_group("A").apply(lambda v: v["B"].sum())
```

**Exploration**

The reason the `.to_frame()[None]` approach is sub-optimal, is because interally, the batch has an iterator of (label, container) pairs.

If we examine one of these pairs, we can see the following:

```python
label, container = next(iter(batch.items()))
print(container)
<Series>
<Index>
None     1.0
<object> <float64>
```

This is not good, because we are packing the result of the sum operation, which is a single float, into a single-element Series container, which then subsequently has to be extracted back out.

My suggestion is to update how a Batch object creates another Batch object. Instead of creating a new Batch from a iterator of (label, container), Batches can be created from an iterator of (label, _components needed to create a container_).

This way, when the final Batch object is realized using `.to_series()`, or items, and it discovers that a simple series can be directly returned, it doesn't have to extract out values from single-element series, but rather, build a series directly.

I think this could be good, because the containers streamed from one Batch into another, have to be created sometime. Right now, that creation time is done before the results are streamed, greatly limiting the flexibility of the resulting Batch object to perform optimizations.

**Platform**

```python
<Series: platform>
<Index>
platform           Linux-5.4.0-87-generic-x86_64-with-glibc2.27
sys.version        3.8.12 (default, Sep 30 2021, 12:39:01) [GCC 7.5.0]
static-frame       0.8.20
numpy              1.17.4
pandas             0.24.2
xlsxwriter         1.1.5
openpyxl           2.5.4
xarray             <ModuleNotFoundError>
tables             3.6.1
pyarrow            0.17.0
msgpack            <ModuleNotFoundError>
msgpack_numpy      <ModuleNotFoundError>
<<U13>             <object>

```

**Comment by flexatone** [comment]
Many thanks for this request. The shortcoming you raise has been on my mind, but I had not found a solution. Your suggestion made a practical approach clear.

Previously, each processing stage of a `Batch` was calling a `normalize_container()` function on each value to insure that `np.ndarray` or elements were wrapped in a `Frame` or `Series` for consistent down-stream processing. Now, `normalize_container()` is only called as part of `to_frame()`, or explicitly (for backwards compatibility, or other purposes) with a new `via_container` property.

As you point out, this improves efficiency by reducing intermediate containers and numerous `isinstance()` checks.

A new `to_series()` method (delegating to `Series.from_items()` can now be implemented as expected.

```python
>>> frame = sf.Frame.from_records([["A", 1.0], ["B", 2.0], ["C", 3.0], ["C", 4.0]], columns=tuple("AB"))
>>> sf.Batch(frame.iter_group_items("A"))["B"].sum().to_series()
<Series>
<Index>
A        1.0
B        2.0
C        7.0
<<U1>    <float64>
```

As this is a non backward compatible change, this will have to wait for the 0.9 release. The PR is here: https://github.com/InvestmentSystems/static-frame/pull/381
