### ISSUE TITLE
Single Column Frame Keyerror if string passed to columns input argument

### ISSUE THREAD

**Issue by naveendaftari** [InvestmentSystems/static-frame#412]
**Description**

I can create a frame from_element and pass a string into the columns argument. However, if I try to access the column with the string used to create the frame, I get a KeyError. Also, if I pass a string into the columns argument with any repeated letters, say 'foto', I get an ErrorInitIndexNonUnique. 

It seems like the construction of the frame should error out if I provide a single string and not an iterable of strings...

Using static_frame 0.8.30

```python
>>> import static_frame as sf
>>> col_name = 'bar'
>>> bar = sf.Frame.from_element(1, index=range(5), columns=col_name)
>>> bar[col_name]
KeyError: 'bar'

>>> col_name = 'bara'
>>> bar = sf.Frame.from_element(1, index=range(5), columns=col_name)
ErrorInitIndexNonUnique: Labels have 1 non-unique values, including 'a'.

# pass col_name as a list into columns
>>> bar = sf.Frame.from_element(1, index=range(5), columns=[col_name])
>>> bar[col_name] # Gives the correct series
```

**Comment by flexatone** [comment]
Many thanks for isolating this issue. 

What you found is that any `Index` initialized with a single string (unless that is a single character) can produce an `Index` in a very bad state. 

From 0.8.34, a proper exception will be raised:

```
>>> sf.Frame.from_element(1, index=range(5), columns='bar') 
ErrorInitIndex: Cannot create an Index from a single string; provide an iterable of strings.
```
