### ISSUE TITLE
IndexDate will coerce a IndexYearMonth into an IndexDate upon intersection and vice versa.

### ISSUE THREAD

**Issue by gettodaze** [InvestmentSystems/static-frame#415]
**Description**

An `IndexDate` will coerce an `IndexYearMonth` into an `IndexDate` upon intersection and vice versa.

**Example**

Provide an interactive Python session, or Python code, to demonstrate the issue. Please keep example data to a minimum.

```python
In [10]: index_ym = sf.IndexYearMonth.from_year_month_range('2021-01', '2021-05')                                     

In [11]: index_date = sf.IndexDate(index_ym)                                                                          

In [12]: index_ym.intersection(index_date)                                                                            
Out[12]: 
<IndexYearMonth>
2021-01
2021-02
2021-03
2021-04
2021-05
<datetime64[M]>

In [13]: index_date.intersection(index_ym)                                                                            
Out[13]: 
<IndexDate>
2021-01-01
2021-02-01
2021-03-01
2021-04-01
2021-05-01
<datetime64[D]>

```

**Platform**

Run the following function (static-frame >= 0.8.1) and provide the results to define your platform and environment:

```python
>>> import static_frame as sf
>>> sf.Platform.display()

<Series: platform>
<Index>
platform           Linux-5.4.0-90-generic-x86_64-with-glibc2.27
sys.version        3.8.12 (default, Dec  8 2021, 09:23:03) [GCC 7.5.0]
static-frame       0.8.31
numpy              1.17.4
pandas             0.24.2
xlsxwriter         1.1.5
openpyxl           3.0.9
xarray             <ModuleNotFoundError>
tables             3.6.1
pyarrow            0.17.0
msgpack            (1, 0, 0)
msgpack_numpy      None
<<U13>             <object>

```

**Comment by flexatone** [comment]
Many thanks for isolating this issue. I am not sure what the best course to take is, as the result of the intersection needs to be an array, and these two different units cannot live in the same array; the result could be an object array containing dt64 elements, but that might be even more odd. We could choose to raise and force the user to `astype` before proceeding. What do you suggest?

**Comment by flexatone** [comment]
On further reflection, I think the only correct thing to do here is  raise an exception if trying to do set operations on different units. This forces the caller to explicit coerce types if that is what they want.

**Comment by gettodaze** [comment]
Yeah, sorry I was at game time. That's similar to what I was thinking to, just to raise in any class mismatch situation.

**Comment by flexatone** [comment]
Thanks again for isolating this issue. This behavior has been changed in 0.8.34 to raise an Exception on any dt64 set comparison of unmatched units. This forces the user to explicitly `astype` before such comparisons.

```python
>>> index_ym = sf.IndexYearMonth.from_year_month_range('2021-01', '2021-05') 
>>> index_date = sf.IndexDate(index_ym)  
>>> index_ym.intersection(index_date) 
static_frame.core.exception.InvalidDatetime64Comparison: Cannot perform set operations on datetime64 of different units; use astype to align units before comparison.
```
