### ISSUE TITLE
make `Series`, `Frame` hashable

### ISSUE THREAD

**Issue by CrepeGoat** [InvestmentSystems/static-frame#42]
Since `static_frame` objects are immutable, is there any reason they can't (or shouldn't) implement `__hash__`?

**Comment by brandtbucher** [comment]
I think it's important to remember that “immutable” doesn’t necessarily mean “hashable”, especially when dealing with containers. Tuples, while immutable, are only hashable when all of their contained items are hashable.

A `Series` or `Frame` can hold references to arbitrary mutable Python objects, so a hash implementation would need to be sensitive to the hashablilty of all contained items. I personally don't really see a use case for this, but maybe your needs are different?

**Comment by flexatone** [comment]
Thanks for this question. While it might be straightforward in some cases (such as when the underlying NumPy arrays are not of type object), another challenge is the implementation of `__eq__`. Following the tradition of NP and Pandas, equality comparisons of same-sized Series result in a Boolean Series. This will break general assumptions of hashability, which expect `__eq__` to return a simple Boolean.

Can you describe a bit of what use case you have in mind?

**Comment by CrepeGoat** [comment]
@brandtbucher @flexatone thanks for replying!

> Can you describe a bit of what use case you have in mind?

I admit my use case is likely not common, but here it goes.

I have a problem that I'm trying to solve using a dynamic-programming-esk approach; by that I mean that I start with some "state", and every time I process a state I generate 0+ additional branching states, which all have to be processed to find the result, so I process every state one by one until none remain. However, some states are redundant; two states might produce the same branching state, and I'd like to increase my efficiency by lumping like-states together. Thus, for state-lumping, I store all states in a (ordered) set/dictionary.

The "states" for my problem are each effectively defined as a mapping from text to integers, but for this to work the mapping object must be hashable. And since I do some pandas.Series magic on the states when processing them, I figured `static_frame` would be the way to go. It would give me a mapping object that:
1. enabled magical processing tricks, like index-wise operations, index-wise aggregation, etc.
2. was immutable *and thus hashable*

`pandas.Series` has 1 but not 2, and something like `tuple`/`namedtuple` has 2 but not 1. Hence I found `static_frame`.

Since I needed that, I wrote my own very simple implementation just to get things to run, and this worked fine:

    class Series(sf.Series):
        def __hash__(self):
            return hash(
                (tuple(self.index), tuple(self.values))
            )

What I'm realizing is that, while you *could* make `sf.Series` hashable (though the `__eq__` bit sounds like a non-trivial hiccup), it would be an additional library feature that would have to be tested & maintained, and it may not be worth maintaining a feature that nobody uses except for that one guy (me). Which of course is up to the dev team.

I expect a resounding "not worth", but I am curious what you all think & why.

**Comment by flexatone** [comment]
Thanks for your thoughts on this issue. While I am attracted to the idea of a hashable `Series` and `Frame`, I think the `__eq__` issue makes this, as you say, non trivial. I will close this for now, but your example of how to derive a simple hashable subclass is a good reference for others.
