### ISSUE TITLE
Add `iter_group_array`, `iter_group_array_items` like `iter_window_array`, `iter_window_array_items`

### ISSUE THREAD

**Issue by flexatone** [InvestmentSystems/static-frame#432]

**Comment by Vandinimodi1595** [comment]
@flexatone, May I know the issue in detail? I would like to contribute to this issue.

**Comment by flexatone** [comment]
Hi @Vandinimodi1595 , many thanks for your offer to contribute.

The starting place for this implementation would be adding an `as_array` Boolean flag (defaulting to False) in `Frame._axis_group_iloc_items()` that, when True, yields arrays instead of wrapping the returned `TypeBlocks` in a `Frame`.

The most efficient implementation would carry that `as_array` Boolean all the way into the functions `type_blocks.group_match()` and `type_blocks.group_sort()`, where instead of calling `TypeBlocks._extract()` you would call `TypeBlocks._extract_array()`.

I am afraid that, despite the "good first issue" tag, this might a little involved depending your experience with NumPy and StaticFrame. If you are interested in something that might be a little less involved, I can suggest some alternative issues.

**Comment by Vandinimodi1595** [comment]
@flexatone, I am doing this as part of my university project and very much excited to accomplish what is required. However, you can always suggest if you are aware of some alternative issues. I might end up working on more than one issue!

**Comment by flexatone** [comment]
Hi @Vandinimodi1595 , sounds good.

I would start by just working on implementing the necessary changes to `type_blocks.group_match()` and `type_blocks.group_sort()`. These can be tested in isolation before we get to integrating this in `Frame`. You will see in `test_type_blocks.py` there are already some isolated tests of `group_sort` and `group_match`; you can put your tests in that module. (Please also note that StaticFrame as 100% test coverage, you will want to be sure that your tests cover every new line.)

Feel free to do this first step and push a draft PR; I am happy to provide feedback as you progress, so just let me know when you have something to look at.

**Comment by Vandinimodi1595** [comment]
> Hi @Vandinimodi1595 ; please confirm if you are still interested in working on this issue.

Hi @flexatone , I apologize for the delay. Yes, I am still interested in working on this issue. I just took deep dive into it and saw group_match and group_sort methods inside the test_type_blocks.py file. I have a few questions about the same. I am not able to install 'unittest' and 'frame_fixtures' in PyCharm. Also, you mentioned that I can run both methods in isolation as well. Could you please elaborate how ?

**Comment by flexatone** [comment]
Hi @Vandinimodi1595.

Please create a virtual environment via "requirements-test.txt" ; if that does not work for you (on some platforms there might be a problem) you can try using "requirements-test-forward.txt". Either is fine; both will give you `frame_fixtures` and everything else you need. After setting up this virtual environment, running `invoke test` should run all tests and all should pass. Please set this up before proceeding.

If we just start with `type_blocks.group_match()`, the first thing we need to do is to extend this function to take an `as_array` Boolean. This function is a little more complex now as I have recently added an `extract` parameter that, when enabled, returns array. So we need so specialize the selection of `func` for the case where `extract` is not being used. It might be as simple as this:

```python
    if axis == 0:
        if extract is not None:
            column_key = extract
            func = blocks._extract_array
        else:
            column_key = None if not drop else drop_mask
            func = blocks._extract if not as_array else blocks._extract_array # this is changed
    else:
        if extract is not None:
            row_key = extract
            func = blocks._extract_array
        else:
            row_key = None if not drop else drop_mask
            func = blocks._extract if not as_array else blocks._extract_array # this is changed
```
I would proceed by, in a PR, implementing these changes on `type_blocks.group_match()` and implement at least one test.

**Comment by Vandinimodi1595** [comment]
@flexatone Thank you for the information. I will proceed as you suggested.

**Comment by flexatone** [comment]
This feature has been completed and will be part of the 0.9.3 release.
