### ISSUE TITLE
Invertible HLoc

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#434]
**Description**

`HLoc` is a useful feature for selecting from an `IndexHierarchy` based on a partial match, e.g. a match from a single level. I wonder if its usefulness could be extended to support negative matches (selecting everything that does not match the given HLoc). 

**Example**

Here's an example where I think this would be useful. Given the following frame:

```python
    columns = sf.IndexHierarchy.from_labels(
        (
            ("info", "identifier"),
            ("info", "company_name"),
            ("price", date(2021, 2, 1)),
            ("price", date(2021, 3, 1)),
            ("volume", date(2021, 2, 1)),
            ("volume", date(2021, 3, 1)),
        )
    )
    frame = sf.Frame.from_records(
        [
            ("01234", "CompanyA", 0.1, 0.9, 10000, 20000),
            ("09878", "CompanyB", 0.2, 0.8, 10000, 20000),
        ],
        columns=columns,
    )
```

```
<Frame>
<IndexHierarchy> info       info         price      price      volume     volume     <<U6>
                 identifier company_name 2021-02-01 2021-03-01 2021-02-01 2021-03-01 <object>
<Index>
0                01234      CompanyA     0.1        0.9        10000      20000
1                09878      CompanyB     0.2        0.8        10000      20000
<int64>          <<U5>      <<U8>        <float64>  <float64>  <int64>    <int64>
```

Imagine I want to split it into two pieces, the `info` (string) section and the `data` (numeric) section. I can do the first part using HLoc:

```python
info_selector = sf.HLoc["info", :]
info = frame[info_selector]
```
```
<Frame>
<IndexHierarchy> info       info         <<U4>
                 identifier company_name <<U12>
<Index>
0                01234      CompanyA
1                09878      CompanyB
<int64>          <<U5>      <<U8>
```

But the second part is more complicated. I need to select everything that does not have 'info' as its outer level. I can accomplish it using `values_at_depth`, but it would be nice if I could simply invert `info_selector`

```python
data_selector = data.columns.values_at_depth(0) != "info"

# What I want:
data_selector = ~info_selector

data = frame[data_selector]
```
```
<Frame>
<IndexHierarchy> price      price      volume     volume     <<U6>
                 2021-02-01 2021-03-01 2021-02-01 2021-03-01 <object>
<Index>
0                0.1        0.9        10000      20000
1                0.2        0.8        10000      20000
<int64>          <float64>  <float64>  <int64>    <int64>
```

**Platform**

Run the following function (static-frame >= 0.8.1) and provide the results to define your platform and environment:

```python
>>> import static_frame as sf
>>> sf.Platform.display()

<Series: platform>
<Index>
platform           Linux-5.13.0-28-generic-x86_64-with
sys.version        3.8.12 (default, Jan 26 2022, 10:31:25) [GCC 7.5.0]
static-frame       0.8.34
numpy              1.17.4
pandas             0.24.2
xlsxwriter         1.1.5
openpyxl           3.0.9
xarray             0.18.0
tables             3.6.1
pyarrow            0.17.0
msgpack            (1, 0, 0)
msgpack_numpy      None
<<U13>             <object>
```

**Comment by flexatone** [comment]
Many thanks for this interesting idea. I wonder if it should be generalized: why not have all selection routines be optionally invertible? Let me give some thought to possible interfaces.

**Comment by ForeverWintr** [comment]
I suppose you could introduce `.nloc` and `.niloc` (where *n* stands for negate). Selections that result in a boolean array are already invertible (`s.loc[~(s['a'] == 5)]`) so inverting `sf.HLoc` felt to me like a natural parallel.

**Comment by flexatone** [comment]
@gettodaze pointed out recently that the an inverted selection is the same as `drop`, and `drop` should already support all types of selection, including `HLoc`. Might that cover this need?

**Comment by ForeverWintr** [comment]
Interesting! Yes, I think that would cover this need.

**Comment by flexatone** [comment]
Great. I think the `drop` interfaces cover what we would want here so for now I will close this issue.
