### ISSUE TITLE
"groupby" aggregation on index hierarchy levels

### ISSUE THREAD

**Issue by CrepeGoat** [InvestmentSystems/static-frame#44]
I have a `static_frame.Series`, like so:
```python
import static_frame as sf
import numpy as np
    
colors = ('red', 'green')
shapes = ('square', 'circle', 'triangle')
    
series = sf.Series(np.arange(6), index=sf.IndexHierarchy.from_product(shapes, colors))
```

I want to be able to perform some "groupby" function, like summing all like-color values together into a new `Series` that looks something like this:
```
<IndexHierarchy>       <Series>
red   6
green 9
<<U8> <int64>
```

With a `pandas.Series`, I could do this:
```python
agg_series = series.groupby(level=1).sum()
```

However as far as I can tell, there's no way to do this with `static_frame` objects (without building the result manually). The closest functionality I can find is [the group iterator functions](https://static-frame.readthedocs.io/en/latest/api_iter.html#id1), but those don't let you group by index hierarchy levels.

I understand that `static_frame` is not intended as a drop-in replacement for `pandas`, but this seems like a desirable feature for any data-crunching library.

**Comment by flexatone** [comment]
Thanks for your suggestion; I too agree that supporting this functionality is valuable. Some thought will need to be given to the interface, however. For example, when you use this type of grouping, are you more often grouping only on the hierarchical index, or also on the values (or, in the case of a Frame) on one or more columns?

**Comment by CrepeGoat** [comment]
The interface is definitely an area for consideration; while `static_frame` prioritizes clarity as a design virtue, the `pandas.(DataFrame/Series).groupby` object is basically a black box of magic. So I imagine that in itself will have to be reworked. In my mind, something like `sf.aggregate_on_index(series, func=sf.Series.sum, level=...)` seems more transparent as to what is happening.

Regarding use cases: I'm sure both come up, but I'm not sure I can say I use `pandas`/big data crunching tools enough to say one way or the other. On the one hand, the first use case makes sense because indices are what define the context of your data, so it makes more sense to aggregate over all values in a certain context. And if you implement the first use case, a user can always perform something similar to the second use case by re-indexing their data. On the other hand reindexing just for a single aggregation might be wasteful, and if users need it consistently enough it would become a problem.

But from what I've seen of the library, most functions are written to be *very* specific in what they do. And if this new feature follows that trend, the first and second use cases would likely be written as different functions anyway. So I think there's no harm in implementing one, seeing what happens, and implementing the second if/when users request it.

**Comment by flexatone** [comment]
Thanks for your thoughts on the interface and use cases.

Avoiding black boxes of magic is important to us! As you note, discrete functions for this type of grouping makes sense.

Assuming we are fine grouping only on the index, adding two new functions to the family of `iter_*` methods, `iter_group_index()` and `iter_group_index_items()`, offers a nice way to support this, and automatically supports doing function application on the returned iterator, exactly as it is available for all other iterators in StaticFrame. So, extending your example, we could now do the following.

```python
>>> colors = ('red', 'green') 
>>> shapes = ('square', 'circle', 'triangle')
>>> s1 = sf.Series(range(6), index=sf.IndexHierarchy.from_product(shapes, colors))
>>> s1
<Series>
<IndexHierarchy>
square           red   0
square           green 1
circle           red   2
circle           green 3
triangle         red   4
triangle         green 5
<<U8>            <<U8> <int64>

>>> s1.iter_group_index(0).apply(np.sum)
<Series>
<Index>
circle   5
square   1
triangle 9
<<U8>    <int64>

>>> s1.iter_group_index(1).apply(np.sum)
<Series>
<Index>
green    9
red      6
<<U5>    <int64>
```
This will also work if you want to select more than one level from the `IndexHierarchy`. However, at this time the `apply` will give back an `Index` of tuples rather than an `IndexHierarchy`. More thought will need to go into what is best in these kinds of situations.

```python
>>> textures = ('smooth', 'rough')
>>> s2 = sf.Series(range(12), index=sf.IndexHierarchy.from_product(shapes, colors, textures))
>>> s2.iter_group_index((0, 2)).apply(np.sum)
<Series>
<Index>
('circle', 'rough')  12
('circle', 'smooth') 10
('square', 'rough')  4
('square', 'smooth') 2
('triangle', 'rou... 20
('triangle', 'smo... 18
<object>             <int64>
```
If you would like to try it out, I have pushed this change. I will also do a new release including this addition later today.

**Comment by CrepeGoat** [comment]
Sorry for the late reply. I'm very impressed you made that change so quickly! (I usually expect dead code bases with a handful of not-so-active maintainers) Thanks so much for your effort! I haven't had the chance to try it out yet, but if the examples you posted work as promised then it should do exactly what I want :)

**Comment by flexatone** [comment]
No problem; thanks for identifying the need for such a practical feature!

**Comment by CrepeGoat** [comment]
One question: what's the index sorting behavior like? From some cursory tests (using a mix of `int`s and `str`s for index values) it doesn't appear to require sortable index values; however the resulting index appears to have some kind of sorting, and it's definitely not based on that of the original series index (as demonstrated in your examples).
