### ISSUE TITLE
Example animation in README takes too much resource to render

### ISSUE THREAD

**Issue by chaichontat** [InvestmentSystems/static-frame#447]
The example SVG animation takes so much resource to render that it saturates an M1 CPU core and slows the entire GitHub page. This happens in both Safari and Chrome in Mac.

https://github.com/InvestmentSystems/static-frame/blob/2b948d631400bdf7eb9c4b535609b111c77ae5ce/README.rst?plain=1#L79

It's 1.2 MB big and stutters. Would it be better to use a simpler GIF instead?

**Comment by flexatone** [comment]
Thank you for this feedback. The performance cost of that SVG seems to vary greatly by platform and browser, so I have removed it for now. Thanks again.
