### ISSUE TITLE
Creation of empty IndexHierarchy fails with from_labels and reorder_for_hierarchy

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#461]
**Description**

It's possible to create an empty `IndexHierarchy` with `sf.IndexHierarchy.from_labels((), depth_reference=2)`, but the same method fails when `reorder_for_hierarchy` is set. 

**Example**

```python
sf.IndexHierarchy.from_labels((), depth_reference=3, reorder_for_hierarchy=True) 
# static_frame.core.exception.ErrorInitFrame: no rows available in records, and no columns defined.
```

**Platform**

Run the following function (static-frame >= 0.8.1) and provide the results to define your platform and environment:

```python
>>> import static_frame as sf
>>> sf.Platform.display()
<Series: platform>
<Index>
platform           Linux-5.13.0-39-generic-x86_64-with
sys.version        3.8.12 (default, Mar 31 2022, 17:04:30) [GCC 7.5.0]
static-frame       0.8.38
numpy              1.17.4
pandas             0.24.2
xlsxwriter         1.1.5
openpyxl           3.0.9
xarray             0.18.0
tables             3.6.1
pyarrow            0.17.0
msgpack            (1, 0, 0)
msgpack_numpy      None
<<U13>             <object>

```

**Comment by flexatone** [comment]
Thanks for posting this issue.

This appears to be an artifact of the pre 0.9 `IndexHierarchy` implementation. From 0.9 and following, `IndexHierarchy` has been re-implemented and this no longer appears to be an issue.

I will close this issue for now but feel free to reopen if needed.

```python
>>> sf.IndexHierarchy.from_labels((), depth_reference=3, reorder_for_hierarchy=True).shape
(0, 3)
```
