### ISSUE TITLE
Series.dropna() not working as expected on hierarchical-index series

### ISSUE THREAD

**Issue by ThatsGobbles** [InvestmentSystems/static-frame#48]
MVCE:

```
import static_frame as sf
import numpy as np

f = sf.Series(np.nan, index=sf.IndexHierarchy.from_product(['A', 'B'], [1, 2]))
f.dropna()
```

The output will be the unmodified series, with NaNs still present. Surprisingly, Series.fillna() works correctly as expected.

**Comment by flexatone** [comment]
Thanks for this issue. The problem here was that there was no handling for when the result was an empty Series; this has been updated.
