### ISSUE TITLE
Documentation - Add one additional layer of nesting

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/static-frame#513]
**Description**

Right now, when you click on a container in the documentation, it will load the documentation/example for ALL interfaces on that container.

This leads to slow loading times, and oftentimes an overwhelming amount of information.

My suggestion would be to add one additional layer, which is the category for each container.

So clicking on `Series` (for example), will display a page with a table of contents for all it's categories: 
- Constructor
- Exporter
- Attribute
...
- Accessor Fill Value
- Accessor Regular Expression

Then, each of those will load pages that only contain examples/documentation for that category of interfaces on the container.

**Comment by flexatone** [comment]
Agreed! I will explore an implementation.
