### ISSUE TITLE
Static Typing

### ISSUE THREAD

**Issue by brandtbucher** [InvestmentSystems/static-frame#52]
I nominate `mypy`, since it's another project I'm becoming more involved with. I believe this will prove useful as StaticFrame begins interfacing with C code internally. Ideally, we'd use it as a CI job too.

The following modules pass `mypy --strict`:

- [x] `doc/doc_build.py`
- [x] `doc/source/conf.py`
- [x] `setup.py`
- [x] `static_frame/__init__.py`
- [x] `static_frame/__main__.py`
- [x] `static_frame/core/__init__.py`
- [x] `static_frame/core/array_go.py`
- [x] `static_frame/core/display.py`
- [x] `static_frame/core/display_color.py`
- [x] `static_frame/core/display_html_datatables.py`
- [x] `static_frame/core/doc_str.py`
- [x] `static_frame/core/frame.py`
- [x] `static_frame/core/hloc.py`
- [x] `static_frame/core/index.py`
- [x] `static_frame/core/index_base.py`
- [x] `static_frame/core/index_hierarchy.py`
- [x] `static_frame/core/index_level.py`
- [x] `static_frame/core/iter_node.py`
- [x] `static_frame/core/operator_delegate.py`
- [x] `static_frame/core/series.py`
- [x] `static_frame/core/type_blocks.py`
- [x] `static_frame/core/util.py`
- [x] `static_frame/performance/__init__.py`
- [x] `static_frame/performance/core.py`
- [x] `static_frame/performance/main.py`
- [x] `static_frame/performance/perf_test.py`
- [x] `static_frame/performance/pydata_2018.py`
- [x] `static_frame/test/__init__.py`
- [x] `static_frame/test/property/__init__.py`
- [x] `static_frame/test/property/strategies.py`
- [x] `static_frame/test/property/test_index.py`
- [x] `static_frame/test/property/test_strategies.py`
- [x] `static_frame/test/property/test_type_blocks.py`
- [x] `static_frame/test/property/test_util.py`
- [x] `static_frame/test/test_case.py`
- [x] `static_frame/test/unit/__init__.py`
- [x] `static_frame/test/unit/test_array_go.py`
- [x] `static_frame/test/unit/test_display.py`
- [x] `static_frame/test/unit/test_display_color.py`
- [x] `static_frame/test/unit/test_doc.py`
- [x] `static_frame/test/unit/test_frame.py`
- [x] `static_frame/test/unit/test_index.py`
- [x] `static_frame/test/unit/test_index_hierarchy.py`
- [x] `static_frame/test/unit/test_index_level.py`
- [x] `static_frame/test/unit/test_main.py`
- [x] `static_frame/test/unit/test_series.py`
- [x] `static_frame/test/unit/test_type_blocks.py`
- [x] `static_frame/test/unit/test_util.py`

**Comment by brandtbucher** [comment]
@flexatone Now that over half of our modules pass `mypy --strict`, I've added a CI job to keep them that way. We can add more files to `mypy.ini` as we make progress on the remaining ones.

Running `mypy --strict` locally should be a quick way to check that nothing's regressed, too.

**Comment by flexatone** [comment]
The introduction of `SupportsOps`, defining types and interfaces and to be used with `MetaOperatorDelegate`, essentialy created a base class for all containers, something I had been avoiding for no reason other than we did not yet have a need. Now that there was need, a path became clear to make all container inheritance and meta-class application simpler:

1. `SupportsOps` becomes `ContainerBase`, and applies the meta class, now named `ContainerMeta`; all containers (including `IndexBase`) inherit from `ContainerBase`, and `ContainerMeta` does not need to be applied anywhere else. We also avoid doing multiple inheritance (as was done with `SupportsOps`. operator_delegate.py becomes container.py.
2. `IndexBase` gets the type defs that were on `SupportsOpsIndex`

**Comment by brandtbucher** [comment]
Great!

As discussed offline, any `# type: ignore` comments and (especially) `typing.cast` calls are just temporary measures. My next steps will be to refactor code and adjust the mypy settings to remove them entirely (`# type: ignore` comments should only be used for mypy bugs).

I'd also like to integrate the official [NumPy stubs](https://github.com/numpy/numpy-stubs) as well, since all `numpy` imports are treated as `typing.Any` currently. They're still under development, but mature enough for our needs... and we can contribute bug fixes as needed. They can also guide us on how we want to type our generics down the road!

**Comment by flexatone** [comment]
i have the following test code (extracted):

```python
        f2 = FrameGO(a1, columns=('a', 'b'))
        f2 = f2.set_index('a')
        f2 = f2.sort_values('b', ascending=False)
```
mypy complains:

static_frame/test/unit/test_frame.py:2278: error: Incompatible types in assignment (expression has type "Frame", variable has type "FrameGO")
static_frame/test/unit/test_frame.py:2279: error: Incompatible types in assignment (expression has type "Frame", variable has type "FrameGO")

I assume this is because `set_index()` and `sort_values()` are defined on the base class as returning `Frame`.  What is the best way to handle this?

**Comment by brandtbucher** [comment]
If I'm understanding correctly, this is the idiom I've used for situations like these throughout our codebase:

```py
import typing as tp


B = tp.TypeVar("B", bound="MyBase")


class MyBase:

    def some_copy(self: B) -> B:
        ...

    @classmethod
    def some_construction(cis: tp.Type[B]) -> B:
        ...
```

This is one of the rare cases where you actually want to annotate `self` and `cls`!

**Comment by flexatone** [comment]
@brandtbucher: FYI, I had to leave a bunch of `# type: ignore` in `TypeBlocks._fillna_directional_axis_1`. MyPy was complaining about how I was using a few NumPy arrays in a loop, namely `bridging_isna` and `bridging_count`. I tried a trivial type hint for the local variable, but that did not seem to help. I suspect there is a better way!

**Comment by flexatone** [comment]
While there is still more to do and many `type: ignore`s, all core modules are now covered by MyPy.
