### ISSUE TITLE
Add `via_values` support to Batch

### ISSUE THREAD

**Issue by flexatone** [InvestmentSystems/static-frame#543]

**Comment by 9gl** [comment]
Hey @flexatone ,
I'm interested in contributing to this issue, so before I start working on it, would you mind sparing your time explaining what the issue is about and pointing me to some resources to get started.

**Comment by flexatone** [comment]
Many thanks, @9gl , for your interest in working on this! 

I am afraid however that on closer examination this is already implemented! I made mistake when I created this issue. Perhaps you would be interested in working on https://github.com/InvestmentSystems/static-frame/issues/544 instead?
