### ISSUE TITLE
Documentation search bar not searching method names

### ISSUE THREAD

**Issue by gettodaze** [InvestmentSystems/static-frame#553]
**Description**

This might be a known issue, but searches don't seem to search method names.

**Example**

When I search for `loc_max` in the new docs, I only get code results.

https://static-frame.readthedocs.io/en/latest/search.html?q=loc_max&check_keywords=yes&area=default
![image](https://user-images.githubusercontent.com/31834702/182938916-36cbb8d7-48ac-4f7e-a841-bb80bd4ec801.png)

But there is also a `loc_max` method I am hoping to show in the search results.

https://static-frame.readthedocs.io/en/latest/api_detail/frame-method.html#static_frame.Frame.loc_max
![image](https://user-images.githubusercontent.com/31834702/182940305-6b59cbc6-f764-483e-8fae-abac7748f021.png)

**Comment by flexatone** [comment]
Many thanks for raising this issue, I will investigate. I believe this is due to using Jinja for templating the API docs, but there might alternatives.

**Comment by flexatone** [comment]
After looking more closely, I found that I was skipping the addition of many components to the index, removing them from search. At this time I cannot add all end-points to the index, as SF has a hierarchical interface requiring duplicating some API roots (i.e., `iter_element` itself has many methods); but I was able to add many many more than I was previously:

https://static-frame.readthedocs.io/en/latest/genindex.html

Thanks again for bringing this to my attention.
