### ISSUE TITLE
Prettier format for Container Overviews

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/static-frame#556]
Currently, the API overview page for containers is a bit too condensed, and I feel it is personally not visually friendly.

![undesired](https://user-images.githubusercontent.com/16909216/183229245-8a9865db-c7df-4a7a-90a9-d6a8f1edfa7d.png)

I recommend separating each group by lines, and providing brief descriptions of each category.
I believe this will be useful, as a common use case is a user to say, "I want to perform ____ on a Frame.", They will get to this page, and I fear they will not understand what "AccessorString" means, or not immediately know how to interpret the different between "Assignment" and "Iterator" for example.

Here is a rough mockup of what I have in mind:

![DesiredFormat](https://user-images.githubusercontent.com/16909216/183229305-0e56b8ca-9c85-44c9-a945-31198f5de126.png)

**Comment by flexatone** [comment]
Many thanks for this suggestion! I have implemented something very similar to this.
