### ISSUE TITLE
Raise when concatenating unnamed series with `IndexDate` columns.

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#562]
**Description**

When concatenating series into a frame with `IndexDate` columns, an unnamed series is assigned a date in 1970 (positional distance from the epoch, perhaps). I think it would be safer to raise an error in this case, similar to what we do when creating an `IndexDate` from an integer:

```python
sf.IndexDate([0])
# RuntimeError: attempting to create datetime64[D] from an integer, which is generally not desired as the result will be offset from the epoch.
```

**Example**

Provide an interactive Python session, or Python code, to demonstrate the issue. Please keep example data to a minimum.

```python
s = sf.Series([1, 2, 3])
s2 = s.rename(np.datetime64('2022-01-01'))
sf.Frame.from_concat((s, s2), axis=1, columns_constructor=sf.IndexDate)

<Frame>
<IndexDate> 1970-01-01 2022-01-01 <datetime64[D]>
<Index>
0           1          1
1           2          2
2           3          3
<int64>     <int64>    <int64>
```

**Platform**

Run the following function (static-frame >= 0.8.1) and provide the results to define your platform and environment:

```python
>>> import static_frame as sf
>>> sf.Platform.display()
<Series: platform>
<Index>
platform           Linux-5.15.0-46-generic-x86_64-with
sys.version        3.8.12 (default, Aug  8 2022, 13:39:14) [GCC 7.5.0]
static-frame       0.9.10
numpy              1.19.2
pandas             0.25.3
xlsxwriter         1.1.5
openpyxl           3.0.9
xarray             0.18.0
tables             3.6.1
pyarrow            0.17.0
msgpack            (1, 0, 0)
msgpack_numpy      None
<<U13>             <object>
```

**Comment by flexatone** [comment]
Many thanks for isolating this issue. I agree this should raise as with the example of `IndexDate`. This change will be made with merge of the associated PR.
