### ISSUE TITLE
Missing Documentation For `apply_element`

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/static-frame#563]
This function only appears in the source code, not the documentation itself.
https://static-frame.readthedocs.io/en/latest/search.html?q=apply_element&check_keywords=yes&area=default

It probably should be added here: https://static-frame.readthedocs.io/en/latest/api_overview/frame-assignment.html#api-overview-frame-assignment

**Comment by flexatone** [comment]
Many thanks for isolating this issue. This will be corrected with the associated PR.
