### ISSUE TITLE
Fancy Indexing?

### ISSUE THREAD

**Issue by bscully27** [InvestmentSystems/static-frame#574]
I couldn't find any documentation on fancy indexing.  Is that available with static-frame?

Simple numpy example:

```
import numpy as np
N = 10**7

arr = np.random.random_integers(0,99, (N,2))
arr[ arr[:,0] <20]
```

**Comment by flexatone** [comment]
Many thanks for your question.

As many fancy indexing moves can result in duplicated values, returning a labeled container (i.e., a `Series` or `Frame`) is often not possible as StaticFrame forbids non-unique indices. That said, it looks like from your example that you are trying to do a  Boolean selection, which is certainly possible in StaticFrame.

Can you elaborate your example a little bit by defining `arr` and showing the expected output? I might be able to demonstrate how to do a similar thing in StaticFrame, or we might find an opportunity to add or extend an interface to accomplish this.

**Comment by bscully27** [comment]
Thanks for the quick response - I edited my original post for proper numpy array creation.

The example is a 2d array of shape (1000000, 2) then slicing on the 1st column to keep values under 20.  The output would look something like this (with only approx 20% of the original rows).

array([[ 5, 71],
       [13, 50],
       [ 7, 47],
       ...,
       [ 2, 46],
       [ 7, 63],
       [ 6,  0]])

**Comment by flexatone** [comment]
@bscully27 : I will close this issue for now; feel free to re-open or start a new issue if you have further questions.
