### ISSUE TITLE
Spurious test failures.

### ISSUE THREAD

**Issue by brandtbucher** [InvestmentSystems/static-frame#64]
@flexatone, it looks like hypothesis thinks that some of our strategies are too slow. I got this failure on the most recent CI run:

```
================================== FAILURES ===================================
_____________________________ TestUnit.test_mloc ______________________________
self = <static_frame.test.property.test_util.TestUnit testMethod=test_mloc>
    @given(get_array_1d2d())
>   def test_mloc(self, array):
E   hypothesis.errors.FailedHealthCheck: Data generation is extremely slow: Only produced 6 valid examples in 1.03 seconds (0 invalid ones and 0 exceeded maximum size). Try decreasing size of the data you're generating (with e.g.max_size or max_leaves parameters).
E   See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.too_slow to the suppress_health_check settings for this test.
static_frame\test\property\test_util.py:23: FailedHealthCheck
--------------------------------- Hypothesis ----------------------------------
 You can add @seed(34354754663420728835026232451587403921) to this test or run pytest with --hypothesis-seed=34354754663420728835026232451587403921 to reproduce this failure.
```

Only one of the six builds failed, and restarting the job made it pass.

**Comment by flexatone** [comment]
That is interesting! I will need to investigate. Maybe NumPy array generation is heavier than it seems.

**Comment by brandtbucher** [comment]
This happened again on your recent commit.

It failed on the same build (Windows / Python 3.7): https://travis-ci.org/InvestmentSystems/static-frame/jobs/545749368.

**Comment by flexatone** [comment]
yeah, interesting. i will try a few things this afternoon to try to avoid it. i think hypothesis should issue warnings rather than failures in this case!

**Comment by flexatone** [comment]
I hope to have fixed this with tighter constraints on array generation; so far it looks good.

**Comment by flexatone** [comment]
My constraints on array sizes seem to have solved this issue.
