### ISSUE TITLE
Frame doesn't properly handle empty iterators.

### ISSUE THREAD

**Issue by brandtbucher** [InvestmentSystems/static-frame#76]
This is tricky, and probably super-low-priority... `Frame.__init__` is inconsistent in its handling of empty iterators. This is *somewhat* related to your recent changes @flexatone.

The `dtype` changes from `float64` to `object` when the index or columns are an empty iterator.

```py
>>> sf.Frame(index=(), columns=())  # Desired behavior.
<Frame>
<Index>   <float64>
<Index>
<float64>
>>> sf.Frame(index=iter(()), columns=())  # Index becomes object.
<Frame>
<Index>  <float64>
<Index>
<object>
>>> sf.Frame(index=(), columns=iter(()))  # Columns become object.
<Frame>
<Index>   <object>
<Index>
<float64>
```

SF raises if a fill value is passed to an unfillable `Frame`, but this error does not occur if  the index or columns are an empty iterator:

```py
>>> sf.Frame(None, index=(1,2,3), columns=())  # Desired behavior.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bucher/src/static-frame/static_frame/core/frame.py", line 854, in __init__
    raise RuntimeError('cannot supply a single element to Frame constructor when index or columns is empty')
RuntimeError: cannot supply a single element to Frame constructor when index or columns is empty
>>> sf.Frame(None, index=(1,2,3), columns=iter(()))  # Doesn't raise.
<Frame>
<Index> <object>
<Index>
1
2
3
<int64>
```

The opposite problem exists, too:

```py
>>> sf.Frame(index=(1,2,3), columns=())  # Desired behavior.
<Frame>
<Index> <float64>
<Index>
1
2
3
<int64>
>>> sf.Frame(index=(1,2,3), columns=iter(()))  # Raises.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bucher/src/static-frame/static_frame/core/frame.py", line 848, in __init__
    raise RuntimeError('must supply a non-default value for Frame construction from a single element or array constructor input')
RuntimeError: must supply a non-default value for Frame construction from a single element or array constructor input
```

I think lines [814-818](https://github.com/InvestmentSystems/static-frame/blob/7a34989ea7cc1e9cf8c56f4db09a400274ea7710/static_frame/core/frame.py#L814) are part of the issue.

A cheap and easy fix would be to:
 - Make the default dtype of empty blocks `object` (fixes the first example).
 - Don't raise if a fill value is provided for an empty `Frame` (fixes the second example).
 - Defer raising if a fill value isn't passed, until the value is actually used (fixes the third example).

I haven't dug too far into alternatives, but it would probably involve either changing the way the blocks are constructed or collecting iterators into tuples at the start of `Frame.__init__`.

**Comment by brandtbucher** [comment]
If that fix sounds good, I can apply it.

**Comment by flexatone** [comment]
Thanks for isolating this issue. I think this is really two issues; (1) how Index's deal with empty iterators and (2) how Frame observes if a provided index argument is empty or not.  Let me investigate further; while low priority, getting this consistent is desirable.

**Comment by flexatone** [comment]
The first part of this is now fixed, with a refinement to `Index` constructors to identify such zero length cases and not force an object dtype. The second part will take some more thought!

```python
In [2]: sf.Frame(index=(), columns=())                                                    
Out[2]: 
<Frame>
<Index>   <float64>
<Index>
<float64>

In [3]: sf.Frame(index=iter(()), columns=())                                              
Out[3]: 
<Frame>
<Index>   <float64>
<Index>
<float64>

In [4]: sf.Frame(index=(), columns=iter(()))                                              
Out[4]: 
<Frame>
<Index>   <float64>
<Index>
<float64>
```

**Comment by flexatone** [comment]
The second part of this is no fixed. My approach was just to appropriately defer the evaluation of implied shape by index and columns and whether the `data` argument is set until the appropriate times, depending on the initialization approach.

Now the following examples produce the desired results:

```python
In [3]: sf.Frame(None, index=(1,2,3), columns=iter(()))                                                                                                                                                                                                                    
RuntimeError: cannot supply a data argument to Frame constructor when index or columns is empty

In [4]: sf.Frame(index=(1,2,3), columns=iter(()))                                                                                                                                                                                                                          
Out[4]: 
<Frame>
<Index> <float64>
<Index>
1
2
3
<int64>
```
