### ISSUE TITLE
ArrayGO is too lazy.

### ISSUE THREAD

**Issue by brandtbucher** [InvestmentSystems/static-frame#79]
`ArrayGO` doesn't properly validate the types passed to `extend` and `append`:

```py
>>> from static_frame.core.array_go import ArrayGO
>>> a = ArrayGO([1,2,3], dtype=int)
>>> a.append("XXX")
>>> a.values
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bucher/src/static-frame/static_frame/core/array_go.py", line 109, in values
    self._update_array_cache()
  File "/home/bucher/src/static-frame/static_frame/core/array_go.py", line 69, in _update_array_cache
    self._array = np.array(self._array_mutable, self._dtype)
ValueError: invalid literal for int() with base 10: 'XXX'
```

**Comment by flexatone** [comment]
As the doc string for ArrayGO states: "A grow only, one-dimensional, **object** type array, specifically for usage in IndexHierarchy IndexLevel objects."

ArrayGO is implemented only to support, and is only needed in SF, for object arrays. Working with the full range of NP types would require significant additional complexity.

Maybe best thing to do here is to raise NotImplementedError if a dtype other than object is given at initialization.

**Comment by brandtbucher** [comment]
I'll take this one since I'm keeping the C implementation in sync, too.

**Comment by flexatone** [comment]
I have implemented changes to the Python implementation of ArrayGo to enforce object-only arrays.

**Comment by flexatone** [comment]
I am going to close this for now. We can reopen it if we proceed with the C implementation of ArrayGO.
