### ISSUE TITLE
cumprod assumes nan==1

### ISSUE THREAD

**Issue by nekobon** [InvestmentSystems/static-frame#92]
Frame/Series.cumprod method assumes nan==1. 

```python
In [11]: import numpy as np    
In [12]: import static_frame as sf      
In [15]: sf.Series([1,2,np.nan,4,5]).cumprod()            
Out[15]: 
<Series>
<Index>
0        1.0
1        2.0
2        2.0
3        8.0
4        40.0
<int64>  <float64>

```
It's expected to be `[1, 2, nan, nan, nan]` if we follow numpy's behavior. 

```python
In [16]: np.array([1,2,np.nan,4,5]).cumprod()    
Out[16]: array([ 1.,  2., nan, nan, nan])
```

Similarly, Frame/Series.cumsum assumes nan==1 while np.cumsum propagates it.

**Comment by flexatone** [comment]
Here, we are following the pattern of other Series/Frame methods that expose a `skipna` argument, default to `skipna=True`; to observe the nans, you can do the following. If this seems too counter-intuitive, we could change the default, but I think consistency with the other methods is desirable.

```python
In [88]: sf.Series([1,2,np.nan,4,5]).cumprod(skipna=False)  
Out[88]: 
<Series>
<Index>
0        1.0
1        2.0
2        nan
3        nan
4        nan
<int64>  <float64>
```

**Comment by nekobon** [comment]
Thanks!! This argument is very helpful.

I think it makes more sense for `skipna=False` to be their default argument, or provide separate functions to skip na just like numpy (e.g. nansum). It would deviate from pandas interface but I believe more explicit interface is better in long run, even if it makes users always type skipna=True.

This argument was not found in documentation (help(sf.Series.cumprod)) as it shows numpy's cumprod. How can I find all other available arguments for cumprod/cumsum?

**Comment by flexatone** [comment]
Thank you for your thoughts. We can consider changing the default value of `skipna`, which seems more desirable to me than creating 12 more functions explicitly configured for nan.

Thanks also for pointing out the deficiency in the doc strings for these functions. I was simply borrowing the numpy doc string for the non-nan version, which is not entirely helpful. I have started to improve this. As of now,  you will at least get the following:

```python
In [3]: print(sf.Series.cumprod.__doc__)                                                                                                   
Return the cumulative product over the specified axis.

    Args:
        axis: Axis, defaulting to axis 0.
        skipna: Skip missing (NaN) values, defaulting to True.
 ```

**Comment by flexatone** [comment]
I will close this issue and open another to discuss making `skipna` a required argument.
