### ISSUE TITLE
Determine __bool__ functionality

### ISSUE THREAD

**Issue by flexatone** [InvestmentSystems/static-frame#99]
Currently, with `__bool__` not implemented, the default truthiness of `Series` and `Frame` is based on length. This is fine in some cases, but very confusing if `and` or `or` are used instead of `&` or `|`.

**Comment by flexatone** [comment]
For now, for all containers,  `__bool__` will be implemented as `bool(size)`, where `size` is the size of the underling numpy array. This means that `Index`, `Series`, and `Frame` will be truthy when they have data; a `Frame` with an index but no data, or columns and no data, will be falsy.

**Comment by ForeverWintr** [comment]
SF users just have to remember not to do things like this:

```python
a = sf.Series(range(3))
assert a == []
```

**Comment by flexatone** [comment]
Interesting point. The comparison does not have to be to the empty list, of course, but can be any element, whereby we get a Boolean Series back that has non-zero length.

```python
>>> import static_frame as sf 
>>> a = sf.Series(range(3)) 
>>> a == [] 
<Series>
<Index>
0        False
1        False
2        False
<int64>  <bool>
```
